### ISSUE TITLE
GcStats failure to open on certain traces

### ISSUE THREAD

**Issue by swgillespie** [Microsoft/perfview#108]
I have a trace on my machine that fails to open GcStats, failing with this stack trace:

```
Started: Opening GCStats
Completed: Opening GCStats   (Elapsed Time: 2.541 sec)
Exception Occurred: System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at Stats.GcStats.PrintCondemnedReasonsToHtml(TraceGC gc) in E:\GitHub\perfview\src\PerfView\GcStats.cs:line 900
   at Stats.GcStats.PrintEventCondemnedReasonsTable(TextWriter writer, TraceProcess stats, TraceLoadedDotNetRuntime runtime, Int32 start, Predicate`1 filter) in E:\GitHub\perfview\src\PerfView\GcStats.cs:line 805
   at Stats.GcStats.ToHtml(TextWriter writer, TraceProcess stats, TraceLoadedDotNetRuntime runtime, String fileName, Boolean doServerGCReport) in E:\GitHub\perfview\src\PerfView\GcStats.cs:line 177
   at Stats.ClrStats.ToHtml(TextWriter writer, List`1 perProc, String fileName, String title, ReportType type, Boolean justBody, Boolean doServerGCReport) in E:\GitHub\perfview\src\PerfView\ClrStats.cs:line 77
   at PerfView.PerfViewGCStats.WriteHtmlBody(TraceLog dataFile, TextWriter writer, String fileName, TextWriter log) in E:\GitHub\perfview\src\PerfView\PerfViewData.cs:line 2045
   at PerfView.PerfViewHtmlReport.<>c__DisplayClass16_0.<Open>b__0() in E:\GitHub\perfview\src\PerfView\PerfViewData.cs:line 952
   at PerfView.StatusBar.<>c__DisplayClass19_0.<StartWork>b__0(Object <state>) in E:\GitHub\perfview\src\PerfView\GuiUtilities\StatusBar\StatusBar.xaml.cs:line 216
An exceptional condition occurred, see log for details.
```

I've checked this repros on PerfView built from master and doesn't repro on the PerfView currently hosted at `\\clrmain\tools\PerfView.exe`. I doubt I'm allowed to go posting the trace that I have that causes this to repro but I'd be happy to share it privately. I can take a look at this a little later in the week to see if it's an easy fix.

**Comment by swgillespie** [comment]
On a debug build:

```
---- DEBUG ASSERTION FAILED ----
---- Assert Short Message ----

---- Assert Long Message ----

   at Microsoft.Diagnostics.Tracing.Analysis.TraceProcessesExtensions.Processes(TraceEventSource source) in E:\GitHub\perfview\src\traceEvent\Computers\TraceProcess.cs:line 46
   at Microsoft.Diagnostics.Tracing.Analysis.TraceProcessesExtensions.NeedProcesses(TraceEventDispatcher source) in E:\GitHub\perfview\src\traceEvent\Computers\TraceProcess.cs:line 32
   at Microsoft.Diagnostics.Tracing.Analysis.TraceLoadedDotNetRuntimeExtensions.NeedLoadedDotNetRuntimes(TraceEventDispatcher source) in E:\GitHub\perfview\src\traceEvent\Computers\TraceManagedProcess.cs:line 38
   at PerfView.PerfViewGCStats.WriteHtmlBody(TraceLog dataFile, TextWriter writer, String fileName, TextWriter log) in E:\GitHub\perfview\src\PerfView\PerfViewData.cs:line 2036
   at PerfView.PerfViewHtmlReport.<>c__DisplayClass16_0.<Open>b__0() in E:\GitHub\perfview\src\PerfView\PerfViewData.cs:line 952
   at PerfView.StatusBar.<>c__DisplayClass19_0.<StartWork>b__0(Object <state>) in E:\GitHub\perfview\src\PerfView\GuiUtilities\StatusBar\StatusBar.xaml.cs:line 216
   at System.Threading.QueueUserWorkItemCallback.WaitCallback_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()
```

**Comment by vancem** [comment]
If you can place the file on \\clrmain\public\writable\users\vancem somewhere that would be helpful.

**Comment by swgillespie** [comment]
@vancem Done at \\clrmain\public\writable\users\vancem\segilles . I debugged this one a little bit this morning and [this assert](https://github.com/swgillespie/perfview/blob/master/src/TraceEvent/Computers/TraceProcess.cs#L46) seems wrong, since `m_currentSource != source` is checked [https://github.com/swgillespie/perfview/blob/master/src/TraceEvent/Computers/TraceProcess.cs#L33](here). Removing that assert hit another assert later on, though.

**Comment by vancem** [comment]
Thanks, I will take a quick look

**Comment by vancem** [comment]
Sean,  this issue is something that Jeff may have fixed in a pull request that I have just merged.  

Please try it out.   

@jeffschwMSFT  Jeff.  If your PR does not fix Sean's problem do you have bandwidth to take a look?

**Comment by swgillespie** [comment]
Talked to Jeff offline and his PR doesn't fix the issue - he said he'll look into it.

**Comment by vancem** [comment]
Jeff fixed this.
