### ISSUE TITLE
System.IO.FileLoadException while calling TraceEventSession.SetFileName(filename)

### ISSUE THREAD

**Issue by amruthrajv-dev** [microsoft/perfview#1099]
I am calling TraceEventSession.SetFileName(filename) from **multiple process** together and I am getting the below exception.

System.IO.FileLoadException : The process cannot access the file because it is being used by another process. (Exception from HRESULT: 0x80070020)
   at System.Runtime.InteropServices.Marshal.ThrowExceptionForHRInternal(Int32 errorCode, IntPtr errorInfo)
   at Microsoft.Diagnostics.Tracing.Session.TraceEventSession.SetFileName(String newName)

Can someone guide me, what is the best way to use this API when multiple processes are involved.

**Comment by brianrob** [comment]
This is expected because there are multiple processes involved.  You likely will need to do some cross-process synchronization around this call.
