### ISSUE TITLE
perfview can't open trace collected by perfcollect from linux. FormatException

### ISSUE THREAD

**Issue by bozila** [microsoft/perfview#1167]
perfview version 2.0.55. 
.netcore 2.2.8. 
collected perf on linux 16.04. 
getting following error when opening the trace in perfview:
Exception Occurred: System.AggregateException: One or more errors occurred. ---> System.FormatException: Input string was not in a correct format.
   at System.Number.ParseDouble(String value, NumberStyles options, NumberFormatInfo numfmt)
   at Microsoft.Diagnostics.Tracing.StackSources.LinuxPerfScriptEventParser.<NextEvent>d__30.MoveNext()
   at Microsoft.Diagnostics.Tracing.StackSources.LinuxPerfScriptEventParser.<Parse>d__9.MoveNext()
   at Microsoft.Diagnostics.Tracing.StackSources.ParallelLinuxPerfScriptStackSource.<>c__DisplayClass1_1.<DoInterning>b__0(Object givenArrayIndex)

trace file is at https://drive.google.com/file/d/1JyXu2036GpEVRYXg3_t8-28Inaw9mmK5/view?usp=sharing

**Comment by brianrob** [comment]
@bozilla, thanks for reporting this.  Is it possible to share a link that doesn't require an account to download?

**Comment by baal2000** [comment]
Had the same issue in .net core 3 on a linux machine running processes inside and outside docker containers. Perfcollect trace was taken outside of the container per https://gitee.com/git_Epxeon/coreclr/raw/master/Documentation/project-docs/linux-performance-tracing.md.

The error while opening CPU traces in perfview:
```
Started with command line: c:\perfview\perfview
PerfView Version: 2.0.56  BuildDate: Wed, 27 May 2020 11:01:40 GMT
PerfView Start Time 6/15/2020 9:38:25 AM
Started: View
Warning: PdbScope not found at c:\perfview\PerfViewExtensions\PdbScope.exe
Disabling the Image Size Menu Item.
Warning: ILSize not found at c:\perfview\PerfViewExtensions\ILSize.dll
Disabling the IL Size Menu Item.
Completed: View   (Elapsed Time: 0.055 sec)
Started: Opening MGR-54_support31_20200605_2.trace.zip
Creating ETLX file C:\Users\sergepavlov\AppData\Local\Temp\PerfView\MGR-54_support31_20200605_2.trace_8c411d18.etlx from C:\Users\sergepavlov\Downloads\MGR-54_support31_20200605_2.trace.zip
Warning: Trying to open CTF stream failed, no CTF (lttng) information
Completed: Opening MGR-54_support31_20200605_2.trace.zip   (Elapsed Time: 0.081 sec)
Started: Opening CPU Stacks
Completed: Opening CPU Stacks   (Elapsed Time: 1.687 sec)
Exception Occurred: System.AggregateException: One or more errors occurred. ---> System.FormatException: Input string was not in a correct format.
   at System.Number.ParseDouble(String value, NumberStyles options, NumberFormatInfo numfmt)
   at Microsoft.Diagnostics.Tracing.StackSources.LinuxPerfScriptEventParser.<NextEvent>d__30.MoveNext()
   at Microsoft.Diagnostics.Tracing.StackSources.LinuxPerfScriptEventParser.<Parse>d__9.MoveNext()
   at Microsoft.Diagnostics.Tracing.StackSources.ParallelLinuxPerfScriptStackSource.<>c__DisplayClass1_1.<DoInterning>b__0(Object givenArrayIndex)
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.WaitAll(Task[] tasks, Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at Microsoft.Diagnostics.Tracing.StackSources.ParallelLinuxPerfScriptStackSource.DoInterning()
   at Microsoft.Diagnostics.Tracing.StackSources.LinuxPerfScriptStackSource.InternAllLinuxEvents(Stream stream)
   at Microsoft.Diagnostics.Tracing.StackSources.LinuxPerfScriptStackSource..ctor(String path, Boolean doThreadTime)
   at Microsoft.Diagnostics.Tracing.StackSources.ParallelLinuxPerfScriptStackSource..ctor(String path, Boolean doThreadTime)
   at PerfView.LinuxPerfViewData.OpenStackSourceImpl(String streamName, TextWriter log, Double startRelativeMSec, Double endRelativeMSec, Predicate`1 predicate)
   at PerfView.PerfViewStackSource.OpenStackSource(String streamName, TextWriter log, Double startRelativeMSec, Double endRelativeMSec, Predicate`1 predicate)
   at PerfView.PerfViewStackSource.<>c__DisplayClass23_0.<Open>b__0()
   at PerfView.StatusBar.<>c__DisplayClass22_0.<StartWork>b__0()
---> (Inner Exception #0) System.FormatException: Input string was not in a correct format.
   at System.Number.ParseDouble(String value, NumberStyles options, NumberFormatInfo numfmt)
   at Microsoft.Diagnostics.Tracing.StackSources.LinuxPerfScriptEventParser.<NextEvent>d__30.MoveNext()
   at Microsoft.Diagnostics.Tracing.StackSources.LinuxPerfScriptEventParser.<Parse>d__9.MoveNext()
   at Microsoft.Diagnostics.Tracing.StackSources.ParallelLinuxPerfScriptStackSource.<>c__DisplayClass1_1.<DoInterning>b__0(Object givenArrayIndex)
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()<---
```

Tried to roll back Perfview release versions until 2.0.26 was able to successfully parse the trace.

I'll jump the gun by saying that the entry in perf.data.txt breaking the execution flow is

```
5 31465/31465 [000] 24220.961036:    1001001 cpu-clock: 
```
in
```
...
swapper     0/0     [003] 24220.960154:    1001001 cpu-clock: 
	    7fffa75c09f2 native_safe_halt ([kernel.kallsyms])
	    7fffa75c0693 default_idle ([kernel.kallsyms])
	    7fffa6c3c9b5 arch_cpu_idle ([kernel.kallsyms])
	    7fffa75c0b93 default_idle_call ([kernel.kallsyms])
	    7fffa6cdd6ef do_idle ([kernel.kallsyms])
	    7fffa6cdd963 cpu_startup_entry ([kernel.kallsyms])
	    7fffa6c5dce0 start_secondary ([kernel.kallsyms])
	    7fffa6c020d5 secondary_startup_64 ([kernel.kallsyms])

5 31465/31465 [000] 24220.961036:    1001001 cpu-clock: 
	            c620 [unknown] (/lib/x86_64-linux-gnu/ld-2.23.so)
	            40db [unknown] (/lib/x86_64-linux-gnu/ld-2.23.so)
	           198ad [unknown] (/lib/x86_64-linux-gnu/ld-2.23.so)

swapper     0/0     [001] 24220.961062:    1001001 cpu-clock: 
	    7fffa75c09f2 native_safe_halt ([kernel.kallsyms])
	    7fffa75c0693 default_idle ([kernel.kallsyms])
	    7fffa6c3c9b5 arch_cpu_idle ([kernel.kallsyms])
	    7fffa75c0b93 default_idle_call ([kernel.kallsyms])
	    7fffa6cdd6ef do_idle ([kernel.kallsyms])
	    7fffa6cdd963 cpu_startup_entry ([kernel.kallsyms])
	    7fffa6c5dce0 start_secondary ([kernel.kallsyms])
	    7fffa6c020d5 secondary_startup_64 ([kernel.kallsyms])
...
```

Cloned current master branch and ran from IDE.

The check at line 483 misfires
![image](https://user-images.githubusercontent.com/22180333/84789516-4d139f00-afbe-11ea-8c2e-0332f187874f.png)
leading to 
![image](https://user-images.githubusercontent.com/22180333/84789720-89df9600-afbe-11ea-8dd8-afb058ce4491.png)

Compared 2.0.26 release with the 2.0.39 https://github.com/microsoft/perfview/compare/d9c999e972f3464c738fb063782f57c5b63a6279...496a208d8b9ae9fba5f686893257fdfa43222e47 

The line corresponds to the line 465 in 2.0.39 that wasn't there bedore
![image](https://user-images.githubusercontent.com/22180333/84789359-25243b80-afbe-11ea-8f54-536ab3b2c830.png)

Maybe it's the Perfcollect bug not sur. Even if it is it has to be handled gracefully.

**Comment by brianrob** [comment]
@baal2000, looks like you are likely correct.  Do you happen to have a trace that you're willing to share for this?  I'm interested in reproing so that I can make sure that I actually fix the issue.  If you don't want to post the trace here, but are willing to share, you can also send it to me at brianrob [at] microsoft.

**Comment by baal2000** [comment]
@brianrob, emailed the trace.

**Comment by xiangzhai** [comment]
:gsvm-interest

**Comment by xiangzhai** [comment]
Hi @brianrob 

Thanks for your great PerfCollect: `perfcollect view gcstress4.zip`.  It help me to fix `GCStress=0x4` issue for MIPS64.

Thanks,
Leslie Zhai

**Comment by brianrob** [comment]
Glad to hear it xiangzhai.  Also, @bal2000, it seems that I didn't reply to this issue.  You are correct that the problem was the process name.  #1244 fixes this.

**Comment by baal2000** [comment]
@brianrob 
Great, is #1244 released yet?

**Comment by brianrob** [comment]
Not yet, but it will be in the next release.
