### ISSUE TITLE
PerfView64 cannot lookup symbols because loading native DLL fails

### ISSUE THREAD

**Issue by Mek7** [microsoft/perfview#1268]
Hi,
when you run PerfView64 (not PerfView), symbol lookup fails because native dll msdia140.dll cannot be loaded.
From log:
```
[Looking up symbols for ntdll]
Symbol reader _NT_SYMBOL_PATH= {
    C:\Users\<username>\Desktop;
    SRV*D:\Symbols*https://msdl.microsoft.com/download/symbols;
    }
This can be set using the File -> Set Symbol Path dialog on the Stack Viewer.
Created SymbolReader with SymbolPath C:\Users\<username>\Desktop;SRV*D:\Symbols*https://msdl.microsoft.com/download/symbols
Setting SYmbolReaderOptions forces clearing Pdb lookup cache
[Loading symbols for d:\windows\system32\ntdll.dll]
FindSymbolFilePath: *{ Locating PDB ntdll.pdb GUID ff98fe65-248a-4f35-130a-d2bcedc0be37 Age 1 Version 10.0.17763.1192
FindSymbolFilePath: Pdb is for DLL d:\windows\system32\ntdll.dll
FindSymbolFilePath: Checking relative to DLL path d:\windows\system32\ntdll.dll
FindSymbolFilePath: Probed file location d:\windows\system32\ntdll.pdb does not exist
FindSymbolFilePath: Probed file location d:\windows\system32\symbols.pri\retail\dll\ntdll.pdb does not exist
FindSymbolFilePath: Probed file location d:\windows\system32\symbols\retail\dll\ntdll.pdb does not exist
FindSymbolFilePath: Probed file location C:\Users\<username>\Desktop\ntdll.pdb does not exist
FindSymbolFilePath: Found in cache D:\Symbols\ntdll.pdb\FF98FE65248A4F35130AD2BCEDC0BE371\ntdll.pdb
FindSymbolFilePath: *} Successfully found PDB D:\Symbols\ntdll.pdb\FF98FE65248A4F35130AD2BCEDC0BE371\ntdll.pdb GUID ff98fe65-248a-4f35-130a-d2bcedc0be37 Age 1 Version 10.0.17763.1192
An exception occurred during symbol lookup.  Continuing...
Exception: System.ApplicationException: Could not load native DLL C:\Users\<username>\AppData\Roaming\PerfView\native\amd64\msdia140.dll
   at NativeDlls.LoadNative(String simpleName)
   at Dia2Lib.DiaLoader.GetDiaSourceObject()
   at Microsoft.Diagnostics.Symbols.NativeSymbolModule..ctor(SymbolReader reader, String pdbFilePath, Action`1 loadData)
   at Microsoft.Diagnostics.Symbols.SymbolReader.OpenSymbolFile(String pdbFilePath)
   at Microsoft.Diagnostics.Tracing.Etlx.TraceCodeAddresses.OpenPdbForModuleFile(SymbolReader symReader, TraceModuleFile moduleFile)
   at Microsoft.Diagnostics.Tracing.Etlx.TraceCodeAddresses.LookupSymbolsForModule(SymbolReader reader, TraceModuleFile moduleFile, IEnumerator`1 codeAddressIndexCursor, Boolean enumerateAll, Int32& totalAddressCount)
   at Microsoft.Diagnostics.Tracing.Etlx.TraceCodeAddresses.LookupSymbolsForModule(SymbolReader reader, TraceModuleFile file)
Finished Lookup up symbols for ntdll Elapsed Time = 0,009
Completed: Symbol Lookup   (Elapsed Time: 0,080 sec)
Started: Computing Stack Traces
Completed: Computing Stack Traces   (Elapsed Time: 1,739 sec)
```

Using PerfView (not 64bit) it works fine, but I had to copy folder C:\Users\<username>\AppData\Roaming\PerfView\VER.2020-09-16.12.53.26.965 to folder C:\Users\<username>\AppData\Roaming\PerfView\native because the native folder didn't exist.

**Comment by vladimir-cheverdyuk** [comment]
Exactly the same problem here. The same path that does not exist.
I have to use older version of PerfView.

**Comment by brianrob** [comment]
Thank you for reporting this.  I have a fix for this in https://github.com/microsoft/perfview/pull/1274.
