### ISSUE TITLE
Merge is failing: Merge operation failed return code 0x1069

### ISSUE THREAD

**Issue by felipepessoto** [microsoft/perfview#1281]
Stack trace:

Found NGEN pdb C:\symbols\private\UIAutomationProvider.ni.pdb\19f1a7fa00831555e77bc86483ef25791\UIAutomationProvider.ni.pdb
NGEN PDB creation for C:\Windows\assembly\NativeImages_v4.0.30319_32\UIAutomationProvider\19f1a7fa00831555e77bc86483ef2579\UIAutomationProvider.ni.dll took 0.00 Sec
Generating NGEN Pdbs took 7.4 sec
Deleting temp file
Completed: Merging D:\MyUser\Debugging\Perfview\MyProfiling.etl   (Elapsed Time: 23.097 sec)
Exception Occurred: System.AggregateException: One or more errors occurred. ---> System.Exception: Merge operation failed return code 0x1069
   at Microsoft.Diagnostics.Tracing.Extensions.ETWKernelControl.Merge(String[] inputETLFileNames, String outputETLFileName, EVENT_TRACE_MERGE_EXTENDED_DATA flags)
   at Microsoft.Diagnostics.Tracing.ZippedETLWriter.<>c__DisplayClass39_0.<PrepForWrite>b__0()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.WaitAll(Task[] tasks, Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at Microsoft.Diagnostics.Tracing.ZippedETLWriter.PrepForWrite()
   at Microsoft.Diagnostics.Tracing.ZippedETLWriter.WriteArchive(CompressionLevel compressionLevel)
   at PerfView.CommandProcessor.Merge(CommandLineArgs parsedArgs)
   at PerfView.MainWindow.<>c__DisplayClass13_0.<ExecuteCommand>b__0()
   at PerfView.StatusBar.<>c__DisplayClass22_0.<StartWork>b__0()
---> (Inner Exception #0) System.Exception: Merge operation failed return code 0x1069
   at Microsoft.Diagnostics.Tracing.Extensions.ETWKernelControl.Merge(String[] inputETLFileNames, String outputETLFileName, EVENT_TRACE_MERGE_EXTENDED_DATA flags)
   at Microsoft.Diagnostics.Tracing.ZippedETLWriter.<>c__DisplayClass39_0.<PrepForWrite>b__0()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()<---

An exceptional condition occurred, see log for details.

**Comment by brianrob** [comment]
@felipepessoto what version of PerfView did this happen with?  Also, out of curiosity, if you reboot the machine does this go away?  I did some searching of past failures in this space, but it seems that this one is fairly uncommon.

**Comment by felipepessoto** [comment]
I'm using the latest one. But I also tried with an version from July. (but I haven't captured the trace with that version, I only tried to Merge the previously captures etl).

I'll try to reboot the computer

**Comment by felipepessoto** [comment]
It worked after reboot. Thanks

**Comment by felipepessoto** [comment]
Unfortunately the problem is back after some hours :(
Should we keep the issue open to further investigation?

**Comment by kleisauke** [comment]
I had the same issue with [BenchmarkDotNet's `NativeMemoryProfiler`](https://wojciechnagorski.com/2019/08/analyzing-native-memory-allocation-with-benchmarkdotnet/).

The exception occurred when merging various `*.etl` files into a single one on a hard drive that was nearly full. So, make sure your HDD/SSD has enough free space.

**Comment by tamirs9876** [comment]
I also got this error, will appreciate your assistance, @brianrob .

version: `3.1.7`
Command line:
`PerfView /DataFile:file.etl /LogFile:file_log.txt /StackCompression /CircularMB:1000 /MaxCollectSec:600 /FocusProcess:process.exe /KernelEvents:ThreadTime /NoGui /NoNGenRundown /AcceptEula collect`

Merge failure inner exception stack trace from perfview log file:
```
System.Exception: Merge operation failed return code 0x1069  
   at Microsoft.Diagnostics.Tracing.ETWKernelControl.Merge(String[] inputETLFileNames, String outputETLFileName, EVENT_TRACE_MERGE_EXTENDED_DATA flags)
   at Microsoft.Diagnostics.Tracing.ZippedETLWriter.<>c__DisplayClass47_0.<PrepForWrite>b__0()
   at System.Threading.Tasks.Task.Execute()
```

I'm running this on Azure DevOps Windows VM, available disk space >100GB.

**Comment by brianrob** [comment]
FYI, following up on this issue - it appears that this was due to an ETW bug in trace compression.  A workaround is to run without compression, though this is not currently exposed by PerfView.  The bug has been fixed, but will take some time to propagate down to any released operating systems that are scheduled to be patched.
