### ISSUE TITLE
Exception when clicking "Save as preset"

### ISSUE THREAD

**Issue by rauhs** [microsoft/perfview#1334]
Trace:

```
StackTrace:
System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at PerfView.StackWindow.DoSaveAsPreset(Object sender, RoutedEventArgs e)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseEvent(RoutedEventArgs e)
   at System.Windows.Controls.MenuItem.InvokeClickAfterRender(Object arg)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
```

Version 2.0.62. I don't have any presets, this was going to be the first one. I only set one "Save as startup preset" a few days ago (if it matters).

**Comment by ilabutin** [comment]
Thanks for reporting. I'll take a look

**Comment by ilabutin** [comment]
Hi @rauhs 
I was able to reproduce this exception when I was trying to save a preset when GroupPats was empty.
Could you confirm this was your case?

**Comment by rauhs** [comment]
Yes, that seems to be the issue! Sorry, I didn't debug more and tried to find the underlying issue.

**Comment by ilabutin** [comment]
The PR is there. Now we just need to wait for @brianrob to approve it.
