### ISSUE TITLE
Starting PerfView Collect Machine-Wide Latest Fails with "Error: Could not load file or assembly 'Microsoft.Win32.Registry"

### ISSUE THREAD

**Issue by haengel** [microsoft/perfview#1378]
Starting PerfView Collection fails. Status Logs:
Started with command line: "C:\Users\haengel.REDMOND\OneDrive - Microsoft\Desktop\PerfView.exe" /RestartingToElevelate:  /BufferSizeMB:256 /StackCompression GuiCollect
PerfView Version: 2.0.66  BuildDate: Mon, 22 Feb 2021 19:59:47 GMT
PerfView Start Time 2/26/2021 7:00:59 PM
Started: GuiCollect
Warning: PdbScope not found at C:\Users\haengel.REDMOND\OneDrive - Microsoft\Desktop\PerfViewExtensions\PdbScope.exe
Disabling the Image Size Menu Item.
Warning: ILSize not found at C:\Users\haengel.REDMOND\OneDrive - Microsoft\Desktop\PerfViewExtensions\ILSize.dll
Disabling the IL Size Menu Item.
Collection Dialog open.
Completed: GuiCollect   (Elapsed Time: 0.256 sec)
Started: Collecting data C:\Users\haengel.REDMOND\OneDrive - Microsoft\Desktop\PerfViewData.etl
[Kernel Log: C:\Users\haengel.REDMOND\OneDrive - Microsoft\Desktop\PerfViewData.kernel.etl]
Kernel keywords enabled: Default
Aborting tracing for sessions 'NT Kernel Logger' and 'PerfViewSession'.
Insuring .NET Allocation profiler not installed.
Detected 64 bit system, removing 64 bit keys
Completed: Collecting data C:\Users\haengel.REDMOND\OneDrive - Microsoft\Desktop\PerfViewData.etl   (Elapsed Time: 0.687 sec)
Error: Could not load file or assembly 'Microsoft.Win32.Registry, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.

**Comment by haengel** [comment]
I tried downloading Microsoft.Win32.Registry.dll and placing it as a peer to the PerfView.exe. Now I get a different error:
Started with command line: "E:\PerfView (1).exe" 
PerfView Version: 2.0.65  BuildDate: Sat, 23 Jan 2021 00:50:56 GMT
PerfView Start Time 2/27/2021 8:01:57 AM
Started: View
Warning: PdbScope not found at E:\PerfViewExtensions\PdbScope.exe
Disabling the Image Size Menu Item.
Warning: ILSize not found at E:\PerfViewExtensions\ILSize.dll
Disabling the IL Size Menu Item.
Completed: View   (Elapsed Time: 0.174 sec)
Collection Dialog open.
Started: Collecting data E:\PerfViewData.etl
[Kernel Log: E:\PerfViewData.kernel.etl]
Kernel keywords enabled: Process, Thread, ImageLoad
Aborting tracing for sessions 'NT Kernel Logger' and 'PerfViewSession'.
Insuring .NET Allocation profiler not installed.
Detected 64 bit system, removing 64 bit keys
Completed: Collecting data E:\PerfViewData.etl   (Elapsed Time: 0.122 sec)
Exception Occurred: System.ComponentModel.Win32Exception (0x80004005): The specified module could not be found
   at Microsoft.Diagnostics.Tracing.Extensions.ETWKernelControl.LoadKernelTraceControl()
   at Microsoft.Diagnostics.Tracing.Extensions.ETWKernelControl.StartKernelSession(UInt64& TraceHandle, Void* propertyBuff, Int32 propertyBuffLength, STACK_TRACING_EVENT_ID* stackTracingEventIds, Int32 cStackTracingEventIds)
   at Microsoft.Diagnostics.Tracing.Session.TraceEventSession.EnableKernelProvider(Keywords flags, Keywords stackCapture)
   at PerfView.CommandProcessor.Start(CommandLineArgs parsedArgs)
   at PerfView.CommandProcessor.Collect(CommandLineArgs parsedArgs)
   at PerfView.MainWindow.<>c__DisplayClass13_0.<ExecuteCommand>b__0()
   at PerfView.StatusBar.<>c__DisplayClass22_0.<StartWork>b__0()
An exceptional condition occurred, see log for details.
Collection Dialog open.
Started: Collecting data E:\PerfViewData.etl
[Kernel Log: E:\PerfViewData.kernel.etl]
Kernel keywords enabled: Process, Thread, ImageLoad
Completed: Collecting data E:\PerfViewData.etl   (Elapsed Time: 0.067 sec)
Exception Occurred: System.ComponentModel.Win32Exception (0x80004005): The specified module could not be found
   at Microsoft.Diagnostics.Tracing.Extensions.ETWKernelControl.LoadKernelTraceControl()
   at Microsoft.Diagnostics.Tracing.Extensions.ETWKernelControl.StartKernelSession(UInt64& TraceHandle, Void* propertyBuff, Int32 propertyBuffLength, STACK_TRACING_EVENT_ID* stackTracingEventIds, Int32 cStackTracingEventIds)
   at Microsoft.Diagnostics.Tracing.Session.TraceEventSession.EnableKernelProvider(Keywords flags, Keywords stackCapture)
   at PerfView.CommandProcessor.Start(CommandLineArgs parsedArgs)
   at PerfView.CommandProcessor.Collect(CommandLineArgs parsedArgs)
   at PerfView.MainWindow.<>c__DisplayClass13_0.<ExecuteCommand>b__0()
   at PerfView.StatusBar.<>c__DisplayClass22_0.<StartWork>b__0()
An exceptional condition occurred, see log for details.

**Comment by brianrob** [comment]
This sounds like PerfView isn't able to unpack its dependencies into your %userprofile%\appdata\roaming\PerfView directory.  Can you look and see if perhaps this directory isn't writable?  You should expect to see a VER.<Date> directory with all of the dependencies in it.  One thing that might be worth doing is to delete the %userprofile%\appdata\roaming\PerfView directory if it exists, and let PerfView try to re-create it, which it will do each time you run it.

**Comment by haengel** [comment]
I tried deleting this folder and re-running Perf View. I can see there are some dependencies here, e.g Microsoft.Diagnostics.FastSerialization, but no Microsoft.Win32.Registry.
