### ISSUE TITLE
Exception when opening gcdump collected from a process dump file

### ISSUE THREAD

**Issue by code2mars** [microsoft/perfview#1407]
I have generated heap dump file from the existing process dump file using Take heap snapshot from the Dump option and when i tried to open the generated heap dump it throws an error. In the logs I am seeing the below exception.

```
Completed: Opening  Stacks   (Elapsed Time: 0.357 sec)
Started: Looking up high importance PDBs that are locally cached
Completed: Looking up high importance PDBs that are locally cached   (Elapsed Time: 0.003 sec)
Started: Computing Stack Traces
Completed: Computing Stack Traces   (Elapsed Time: 0.021 sec)
Exception Occurred: System.ArgumentException: Illegal characters in path.
   at System.IO.Path.CheckInvalidPathChars(String path, Boolean checkAdditional)
   at System.IO.Path.GetFileName(String path)
   at System.IO.Path.GetFileNameWithoutExtension(String path)
   at Graphs.MemoryGraphStackSource.GetFrameName(StackSourceFrameIndex frameIndex, Boolean verboseName)
   at Diagnostics.Tracing.StackSources.FilterStackSource.GetFrameName(StackSourceFrameIndex frameIndex, Boolean fullName)
   at Microsoft.Diagnostics.Tracing.Stacks.CallTreeNode.FindCallee(StackSourceFrameIndex frameID)
   at Microsoft.Diagnostics.Tracing.Stacks.CallTree.FindTreeNode(StackSourceCallStackIndex stack, RecursionGuard recursionGuard)
   at Microsoft.Diagnostics.Tracing.Stacks.CallTree.AddSample(StackSourceSample sample)
   at Diagnostics.Tracing.StackSources.FilterStackSource.<>c__DisplayClass1_0.<ForEach>b__0(StackSourceSample sample)
   at Graphs.MemoryGraphStackSource.ForEach(Action`1 callback)
   at Diagnostics.Tracing.StackSources.FilterStackSource.ForEach(Action`1 callback)
   at Microsoft.Diagnostics.Tracing.Stacks.CallTree.set_StackSource(StackSource value)
   at PerfView.StackWindow.<>c__DisplayClass26_0.<SetStackSource>b__0()
   at PerfView.StatusBar.<>c__DisplayClass22_0.<StartWork>b__0()
An exceptional condition occurred, see log for details.
```

**Comment by brianrob** [comment]
Bulk closing issues.  Please re-open if needed.
