### ISSUE TITLE
GCStats html fails to open for nettrace traced using dotnet-trace on a linux container

### ISSUE THREAD

**Issue by liorss18** [microsoft/perfview#1545]
When trying to open GCStats by double clicking on it, it says `An exceptional condition occurred, see log for details`.
The log shows the following output (error stack trace at the bottom):

```********** End of the saved log *************
Started: Computing Diff  Stacks baseline  Stacks
Completed: Computing Diff  Stacks baseline  Stacks   (Elapsed Time: 47.639 sec)
Started: Computing Stack Traces
Completed: Computing Stack Traces   (Elapsed Time: 0.726 sec)
Started: Computing Stack Traces
Completed: Computing Stack Traces   (Elapsed Time: 0.880 sec)
Started: Opening dotnet_20211216_083331.nettrace
Creating ETLX file C:\Users\lior\AppData\Local\Temp\PerfView\dotnet_20211216_083331_42f08bc7.etlx from C:\Users\lior\Downloads\dotnet_20211216_083331.nettrace
Collecting a maximum of 20,000,000 events.
[Opening a log file of size 0 MB.]
[Sec    0 Read    131,072 events. At  69,916ms.  Wrote    2MB ( 98%).  EstDone  0 min  0 sec.]
1 distinct processes.
Totals
    10,354 events.
        59 events with stack traces.
         0 events with code addresses in them.
     2,864 total code address instances. (stacks or other)
       307 unique code addresses. 
     2,538 unique stacks.
       261 unique managed methods parsed.
    74,504 CLR method event records.
[Conversion complete 10,354 events.  Conversion took 0 sec.]
A total of 306 symbolic addresses were looked up.
Addresses outside any module: 0 out of 306 (0.0%)
Done with symbolic lookup.
ETL Size 30.905 MB ETLX Size 6.438 MB
Completed: Opening dotnet_20211216_083331.nettrace   (Elapsed Time: 0.388 sec)
Started: Opening GCStats
Completed: Opening GCStats   (Elapsed Time: 0.007 sec)
Exception Occurred: System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at Microsoft.Diagnostics.Tracing.Analysis.TraceLoadedDotNetRuntime.<>c__DisplayClass32_0.<SetupCallbacks>b__16(GCMarkWithTypeTraceData data)
   at Microsoft.Diagnostics.Tracing.TraceEventDispatcher.DoDispatch(TraceEvent anEvent)
   at Microsoft.Diagnostics.Tracing.Etlx.TraceLogEventSource.Process()
   at PerfView.PerfViewGCStats.WriteHtmlBody(TraceLog dataFile, TextWriter writer, String fileName, TextWriter log)
   at PerfView.PerfViewHtmlReport.GenerateReportFile(StatusBar worker, TraceLog trace)
   at PerfView.PerfViewHtmlReport.<>c__DisplayClass17_1.<Open>b__0()
   at PerfView.StatusBar.<>c__DisplayClass22_0.<StartWork>b__0()```


The trace was taken on a docker container running dotnet 6:
```
dotnet  --list-runtimes  
Microsoft.AspNetCore.App 6.0.0 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
Microsoft.NETCore.App 6.0.0 [/usr/share/dotnet/shared/Microsoft.NETCore.App]```

command used to take the trace:
```dotnet-trace collect -p 1 --profile gc-collect```

Thanks

**Comment by liorss18** [comment]
Here's a [link](https://drive.google.com/file/d/106CAoH-JwDvKbKgctwhwbvVRMKn8p761/view?usp=sharing) to the trace.

**Comment by brianrob** [comment]
@liorss18, I was able to successfully open this using PerfView 2.0.73.  Can you try a newer version of PerfView?  I suspect this is due to a breaking change in one of the GC events in .NET 6.

**Comment by brianrob** [comment]
Bulk closing.  Please re-open if needed.
