### ISSUE TITLE
Perfview throw exception on ARM64 OS

### ISSUE THREAD

**Issue by ZhaodongTian** [microsoft/perfview#1586]
does perfview support on ARM64 OS?  I got an exception when run command to collect  profile data. 

Started with command line: PerfView.exe
PerfView Version: 2.0.76  BuildDate: Wed, 02 Mar 2022 00:30:06 GMT
PerfView Start Time 3/10/2022 6:58:45 PM
Started: View
Warning: PdbScope not found at D:\testbits\PerfViewExtensions\PdbScope.exe
Disabling the Image Size Menu Item.
Warning: ILSize not found at D:\testbits\PerfViewExtensions\ILSize.dll
Disabling the IL Size Menu Item.
Completed: View   (Elapsed Time: 1.095 sec)
Collection Dialog open.
Started: Running: "C:\ConsoleApp6.exe"...  See log for output.
Ensuring that the .NET CLR Profiler is installed.
Profiler DLL to load is D:\Users\xxxx\AppData\Roaming\PerfView\VER.2022-03-10.17.37.03.297\x86\EtwClrProfiler.dll
Adding HKLM\Software\Microsoft\.NETFramework\COR* registry keys
**ERROR do not have a ETWClrProfiler.dll for architecture ARM64**
WARNING: Only processes that start after this point will log object allocation events.
[Kernel Log: D:\testbits\PerfViewData.kernel.etl]
Kernel keywords enabled: Default
Aborting tracing for sessions 'NT Kernel Logger' and 'PerfViewSession'.
Ensuring .NET Allocation profiler not installed.
Detected 64 bit system, removing 64 bit keys
Completed: Running: "c:\ConsoleApp6.exe"...  See log for output.   (Elapsed Time: 0.666 sec)
Exception Occurred: System.Runtime.InteropServices.COMException (0x80070032): The request is not supported. (Exception from HRESULT: 0x80070032)
   at System.Runtime.InteropServices.Marshal.ThrowExceptionForHRInternal(Int32 errorCode, IntPtr errorInfo)
   at Microsoft.Diagnostics.Tracing.Session.TraceEventSession.EnableKernelProvider(Keywords flags, Keywords stackCapture)
   at PerfView.CommandProcessor.Start(CommandLineArgs parsedArgs)
   at PerfView.CommandProcessor.Run(CommandLineArgs parsedArgs)
   at PerfView.MainWindow.<>c__DisplayClass13_0.<ExecuteCommand>b__0()
   at PerfView.StatusBar.<>c__DisplayClass22_0.<StartWork>b__0()
An exceptional condition occurred, see log for details.

**Comment by brianrob** [comment]
@ZhaodongTian, yes, PerfView is supported on ARM64.  I have not seen this before.  Can you confirm that PerfView was running as administrator (elevated)?  Normally, if it's not, PerfView will auto-restart elevated, but I want to make sure.

**Comment by ZhaodongTian** [comment]
@brianrob , Yes, I was running perfview as admin.  both arm64 mode and amd64 mode  throw that exception.

**Comment by brianrob** [comment]
Interesting.  Can you try running this command:

`typeperf "Event Tracing for Windows\Total Number of Active Sessions" -sc 1`

This will tell us the number of ETW sessions that are running, which can also cause errors on start.

**Comment by ZhaodongTian** [comment]
the result after running that command : "(PDH-CSV 4.0)","\\<machinename>\Event Tracing for Windows\Total Number of Active Sessions"
"03/14/2022 17:33:58.824","34.000000"

**Comment by brianrob** [comment]
Bulk closing old issues.  Please re-open if this is still an issue that needs attention.

**Comment by AArnott** [comment]
@brianrob, I'm hitting this as well. Can we get this reactivated, please?

```
PerfView Version: 3.0.5  BuildDate: Thu, 22 Sep 2022 22:50:28 GMT
PerfView Start Time 9/27/2022 8:48:02 AM
Started: View
Warning: PdbScope not found at D:\Users\andarno\Downloads\PerfViewExtensions\PdbScope.exe
Disabling the Image Size Menu Item.
Warning: ILSize not found at D:\Users\andarno\Downloads\PerfViewExtensions\ILSize.dll
Disabling the IL Size Menu Item.
Completed: View   (Elapsed Time: 0.139 sec)
Collection Dialog open.
Started: Collecting data D:\Users\andarno\Desktop\SlowFirstLaunchDialog.etl
[Kernel Log: D:\Users\andarno\Desktop\SlowFirstLaunchDialog.kernel.etl]
Kernel keywords enabled: Default
Aborting tracing for sessions 'NT Kernel Logger' and 'PerfViewSession'.
Ensuring .NET Allocation profiler not installed.
Detected 64 bit system, removing 32 bit keys.
Completed: Collecting data D:\Users\andarno\Desktop\SlowFirstLaunchDialog.etl   (Elapsed Time: 0.628 sec)
Exception Occurred: System.Runtime.InteropServices.COMException (0x80070032): The request is not supported. (Exception from HRESULT: 0x80070032)
   at System.Runtime.InteropServices.Marshal.ThrowExceptionForHRInternal(Int32 errorCode, IntPtr errorInfo)
   at Microsoft.Diagnostics.Tracing.Session.TraceEventSession.EnableKernelProvider(Keywords flags, Keywords stackCapture)
   at PerfView.CommandProcessor.Start(CommandLineArgs parsedArgs)
   at PerfView.CommandProcessor.Collect(CommandLineArgs parsedArgs)
   at PerfView.MainWindow.<>c__DisplayClass20_0.<ExecuteCommand>b__0()
   at PerfView.StatusBar.<>c__DisplayClass22_0.<StartWork>b__0()
An exceptional condition occurred, see log for details.
```

I ran the tool you asked for:

```
typeperf "Event Tracing for Windows\Total Number of Active Sessions" -sc 1

"(PDH-CSV 4.0)","\\VSJADE-2301\Event Tracing for Windows\Total Number of Active Sessions"
"09/27/2022 08:56:48.273","33.000000"

The command completed successfully.
```

**Comment by AArnott** [comment]
The perfview.exe process is an x64 process, running under emulation on an arm64 Windows OS.

**Comment by brianrob** [comment]
@AArnott is this running on an arm64 VM or a physical machine?

**Comment by AArnott** [comment]
It's a VM on a physical server machine we own.

**Comment by brianrob** [comment]
Thanks for confirming.  This is expected - the PMU is not currently exposed to the guest OS.
