### ISSUE TITLE
NullReferenceException while attempting to collect events for running .NET 6 process

### ISSUE THREAD

**Issue by zhuman** [microsoft/perfview#1660]
I have a pretty typical .NET 6 desktop WPF application process running. Attempting to use PerfView 3.0.2's "Collect" functionality fails while stopping collection with the following exception in the logs:

```
Warning: failure during CLR Rundown Object reference not set to an instance of an object.
Completed: Collecting data K:\PerfTracing\Dopamine1\PerfViewData.etl   (Elapsed Time: 38.297 sec)
Exception Occurred: System.NullReferenceException: Object reference not set to an instance of an object.
   at PerfView.ProviderParser.ParseProviderSpecs(String[] providerSpecs, String wildCardFileName, TraceEventProviderOptions inputOptions, TextWriter log) in D:\a\_work\1\s\src\PerfView\CommandProcessor.cs:line 3663
   at PerfView.CommandProcessor.DoClrRundownForSession(String fileName, String sessionName, CommandLineArgs parsedArgs) in D:\a\_work\1\s\src\PerfView\CommandProcessor.cs:line 3586
   at PerfView.CommandProcessor.Stop(CommandLineArgs parsedArgs) in D:\a\_work\1\s\src\PerfView\CommandProcessor.cs:line 1300
   at PerfView.CommandProcessor.Collect(CommandLineArgs parsedArgs) in D:\a\_work\1\s\src\PerfView\CommandProcessor.cs:line 216
   at PerfView.MainWindow.<>c__DisplayClass17_0.<ExecuteCommand>b__0() in D:\a\_work\1\s\src\PerfView\MainWindow.xaml.cs:line 1335
   at PerfView.StatusBar.<>c__DisplayClass22_0.<StartWork>b__0() in D:\a\_work\1\s\src\PerfView\GuiUtilities\StatusBar\StatusBar.xaml.cs:line 254
An exceptional condition occurred, see log for details.
```

Here are the settings I'm using, but I've tried lots of variations with the same result. Note that this even repros if I disable the ".NET" checkbox.

<img width="666" alt="image" src="https://user-images.githubusercontent.com/891037/178063299-ad7a90f1-3edf-467b-b35f-be589de99d70.png">

**Comment by brianrob** [comment]
Thanks for reporting this.  It is a regression from https://github.com/microsoft/perfview/pull/1643.  I have posted #1661 to fix it. 
 Older versions of PerfView should not have this issue, so you can work around this by running 3.0 or older.
