### ISSUE TITLE
3.0.6 collect not working on Win server 2012R2 - The specified procedure could not be found exception 

### ISSUE THREAD

**Issue by kirsan31** [microsoft/perfview#1765]
Error with manual run:
![image](https://user-images.githubusercontent.com/17767561/206895182-d96e8d44-8e07-4f4d-bb19-e5d4f9f20e65.png)

Log:
```
[EXECUTING: PerfView /DataFile:D:\EXTERNAL\PerfView\4.123.8370.28342_2022.12.09.11.00.38.etl /Merge:true /zip:true /BufferSizeMB:256 /StackCompression /CircularMB:500 /MaxCollectSec:20 /KernelEvents:ThreadTime /TplEvents:Default /FocusProcess:4732 /logFile=D:\EXTERNAL\PerfView\perfViewRun.log /AcceptEula collect]
[Kernel Log: D:\EXTERNAL\PerfView\4.123.8370.28342_2022.12.09.11.00.38.kernel.etl]
Kernel keywords enabled: ThreadTime
Aborting tracing for sessions 'NT Kernel Logger' and 'PerfViewSession'.
Ensuring .NET Allocation profiler not installed.
Detected 64 bit system, removing 32 bit keys.
[Exception Occurred: System.ComponentModel.Win32Exception (0x80004005): The specified procedure could not be found
   at Microsoft.Diagnostics.Tracing.Extensions.ETWKernelControl.LoadKernelTraceControl()
   at Microsoft.Diagnostics.Tracing.Extensions.ETWKernelControl.StartKernelSession(UInt64& TraceHandle, Void* propertyBuff, Int32 propertyBuffLength, STACK_TRACING_EVENT_ID* stackTracingEventIds, Int32 cStackTracingEventIds)
   at Microsoft.Diagnostics.Tracing.Session.TraceEventSession.EnableKernelProvider(Keywords flags, Keywords stackCapture)
   at PerfView.CommandProcessor.Start(CommandLineArgs parsedArgs)
   at PerfView.CommandProcessor.Collect(CommandLineArgs parsedArgs)
   at PerfView.CommandProcessor.ExecuteCommand(CommandLineArgs parsedArgs)]
```

`2.0.77` working normaly.

Sys. info:
![image](https://user-images.githubusercontent.com/17767561/206894860-222279b9-7f67-4295-9dde-8abe08ed4efd.png)

**Comment by ogarci5** [comment]
Apologies if you have already tried this, but have you tried installing .NET 4.6.2 or above?

I was trying to run PerfView on my Windows Server 2012R2 instance and was getting this error. I read the User Guide and it mentioned.

> PerfView is a V4.6.2 .NET application.   Thus you need to have installed a V4.6.2 .NET Runtime on the machine which you actually run PerfView.   On Windows 10 and Windows Server 2016 has .NET V4.6.2. On other supported OS you can install .NET 4.6.2 from standalone installer.

And the [Microsoft .NET docs](https://learn.microsoft.com/en-us/dotnet/framework/install/on-windows-8-1) state that

> .NET Framework 4.8 is the latest version. It is supported on Windows 8.1 and Windows Server 2012 R2. It's included with Windows 11 and in Windows 10 starting with the May 2019 Update.

I am used to working in Windows Server 2016 and Windows 10 which have .NET included by default, but Windows 8.1 and Windows Server 2012R2 do not. When I checked the server I noticed I didn't have .NET installed and this fixed this error for me. I hope this helps!

**Comment by kirsan31** [comment]
@ogarci5 

> to %APPDATA%\Roaming\PerfView\VER.2022-12-06.12.58.10.548\AMD64\KernelTraceControl.dll
> (the directory where the KernelTraceControl.dll is "missing").

This dll was already there but of a different version:
![image](https://github.com/microsoft/perfview/assets/17767561/f5a7eeed-5a11-45aa-823f-04dcd58c9d76)
But after I replaced it with one from 8.1 sdk performance kit - the problem was solved. Thank you 🙏

**Comment by brianrob** [comment]
This is likely an issue where the version of KTC that PerfView carries is not compatible with Windows 8.1.  Unfortunately, this will mean either using this workaround or using an older version of PerfView.
