### ISSUE TITLE
Unhandled exception when starting PerfView on Windows 8.1

### ISSUE THREAD

**Issue by Anton-V-K** [microsoft/perfview#1773]
An unhanded exception occured.

At this point you can opt to continue, however it is possible that the aborted computation will cause additional failures.   Because PerfView generally only opens files for reading, there is no danger of corrupting  files, so it generally does not hurt to try.   However be on guard for unusual/incorrect behavior going forward.

You can of course exit and restart PerfView to be completely safe.

The fact that this exception went unhanded is a programmer error.   It should be reported so it can be fixed.  Please set along the following stack trace information which will be useful in diagnosing the problem.
```
StackTrace:
System.NullReferenceException: Object reference not set to an instance of an object.
   at PerfView.GuiApp.OnGuiUnhandledException(Object sender, DispatcherUnhandledExceptionEventArgs e)
   at System.Windows.Threading.Dispatcher.CatchException(Exception e)
   at MS.Internal.Threading.ExceptionFilterHelper.TryCatchWhen(Object source, Delegate method, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at MS.Internal.Threading.ExceptionFilterHelper.TryCatchWhen(Object source, Delegate method, Object args, Int32 numArgs, Delegate catchHandler)
```

**Comment by Anton-V-K** [comment]
No specific steps needed.
Download the binary from https://github.com/microsoft/perfview/releases/tag/v3.0.6 and run it on Windows 8.1 Pro N.
The OS is like freshly installed and is running inside VirtualBox (a kind of virtual testing environment).

**Comment by brianrob** [comment]
Thanks for clarifying.  I don't have a Windows 8.1 environment, so this will require some setup.  As an FYI though, Windows 8.1 goes out of support in 5 days: https://support.microsoft.com/en-us/windows/windows-8-1-support-will-end-on-january-10-2023-3cfd4cde-f611-496a-8057-923fba401e93.  Based on this, this issue may not get fixed.

**Comment by kirsan31** [comment]
https://github.com/microsoft/perfview/issues/1765 related?

**Comment by vishnu-cmd** [comment]
I faced similar issue. Then I Cloned the PrefView Solution in Visual studio and while running it I got exception due to environment file path in the system, 
For me there was some invalid file path present in the System Environment Variables. After removing it I was able to execute the  prefView.exe
