### ISSUE TITLE
/InMemoryCircularBuffer is broken

### ISSUE THREAD

**Issue by Maoni0** [microsoft/perfview#310]
I am getting this exception when the commandline contains /InMemoryCircularBuffer:

```
[Exception Occurred: System.AggregateException: One or more errors occurred. ---> System.ApplicationException: Merge operation failed return code 0x80280013
   at Microsoft.Diagnostics.Tracing.Extensions.ETWKernelControl.Merge(String[] inputETLFileNames, String outputETLFileName, EVENT_TRACE_MERGE_EXTENDED_DATA flags)
   at Microsoft.Diagnostics.Tracing.ZippedETLWriter.<>c__DisplayClass35_0.<PrepForWrite>b__0()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
```

**Comment by brianrob** [comment]
I just tested this, and I get a different failure:

```
Exception Occurred: System.Runtime.InteropServices.COMException (0x80070008): Not enough memory resources are available to process this command. (Exception from HRESULT: 0x80070008)
   at System.Runtime.InteropServices.Marshal.ThrowExceptionForHRInternal(Int32 errorCode, IntPtr errorInfo)
   at Microsoft.Diagnostics.Tracing.Session.TraceEventSession.InsureStarted(EVENT_TRACE_PROPERTIES* properties)
   at Microsoft.Diagnostics.Tracing.Session.TraceEventSession.EnableProvider(Guid providerGuid, TraceEventLevel providerLevel, UInt64 matchAnyKeywords, TraceEventProviderOptions options)
   at PerfView.CommandProcessor.EnableUserProvider(TraceEventSession userModeSession, String providerName, Guid providerGuid, TraceEventLevel providerLevel, UInt64 matchAnyKeywords, TraceEventProviderOptions options)
   at PerfView.CommandProcessor.Start(CommandLineArgs parsedArgs)
   at PerfView.CommandProcessor.Collect(CommandLineArgs parsedArgs)
   at PerfView.MainWindow.<>c__DisplayClass13_0.<ExecuteCommand>b__0()
   at PerfView.StatusBar.<>c__DisplayClass22_0.<StartWork>b__0()
```

**Comment by Maoni0** [comment]
yep, that's what our last customer who tried this got as well.

**Comment by ryandle** [comment]
I was trying to use this flag and hit the same exception as Maoni. @brianrob let know if you'd like access to a repro machine.

The hresult 0x80280013 is documented as "An encrypted blob is invalid or was not created by this TPM." which seems pretty odd in this scenario to me (but I don't know much about what is happening with kernel ETW buffers under the hood.)
