### ISSUE TITLE
TestIncludeItemOnCallerCalleeTabCallerAsync  fails locally

### ISSUE THREAD

**Issue by vancem** [Microsoft/perfview#354]
WhenI run all tests in VS2017 I get one failure 

TestIncludeItemOnCallerCalleeTabCallerAsync  

It is not clear if this test is enabled (it does have a 'WorkItem' attribute which may mean it is disabled, but VS runs it.  

Anway it fails, because it is fetching the 'callers' of a caller-callee view and the focus node happens to be ROOT (which does not have a caller, so a Items[0] throws a invalid Index exception).  

It is not clear to me what the intent of the test is (it seems like the test should never have worked).  It should probably select some other node besides root for the focus node.  

@sharwell 

Also, the automated tests succeed.   It is not clear why this fails locally but not in the automated run.   That is concerning...

**Comment by sharwell** [comment]
@vancem I can't reproduce this. What's supposed to happen is the following:

* If we're trying to test the callees grid and it's empty, double click the first item in the callers list, which changes the current focus node to a node we know has a callee.
* If we're trying to test the callers grid and it's empty, double click the first item in the callees list, which changes the current focus node to a node we know has a caller.

The handling is here:

https://github.com/Microsoft/perfview/blob/fbca7255dc5c3f78e2c5e5d33ce29001f8c99f50/src/PerfView.Tests/StackViewer/StackWindowTests.cs#L183-L210

This test is part of a comprehensive regression test for #316. It ensures the context menu behaves properly in all potential contexts. Each context is handled separately, and previously this handling had some bugs, so a simple test of a subset of the known grids is not sufficient to detect regressions.

**Comment by mikkelbu** [comment]
@sharwell this test is failing on my machine every time I execute it. Setup:
* VisualStudio.15.Release/15.3.5+26730.16
* Standing on the commit 118f6bc, but with the addition of `<WindowsTargetPlatformVersion>10.0.15063.0</WindowsTargetPlatformVersion>` in both vcxproj-files (otherwise I get `Cannot open include file: 'assert.h': No such file or directory` when compiling `perfview\src\etwclrprofiler\stdafx.h`)
* The tests are executed following the description in CONTRIBUTING.md by selecting Test -> Run -> All Tests from within VS.

I've attached the full error message from the failing test (the stacktrace is not that usable, due to lambdas etc.). [Perfview_Test_ErrorMessage.txt](https://github.com/Microsoft/perfview/files/1484000/Perfview_Test_ErrorMessage.txt)

Ps. When the test was re-enabled in #383, the PR wrongly mentioned that it closes #364 (and not the current issue #354)

**Comment by vancem** [comment]
For what is worth, I noticed that this test failed for me as well after it was re-enabled and I just tried it and it failed).   I have been meaning to get back to Sam with enough so he could investigate, but have had bigger fish to fry...

**Comment by sharwell** [comment]
I see one failure of this test here:
https://ci.appveyor.com/project/sharwell/perfview/build/1.0.532

The output suggests that an exception was thrown by the delegate passed in a call to `StartWork`, but I can't see that exception. If you managed to capture an ETL where I could review exceptions, I believe I could track this down.

:question: I put the test locally in a loop that ran hundreds of times in debug and release builds and I still have not seen a failure. Does this reproduce for y'all when running the failing test by itself, or only when running all tests?

**Comment by mikkelbu** [comment]
@sharwell  On my computer it fails every time (both when I run the test individually or when I run all the tests and both in Debug and Release). 

The line that fails is
https://github.com/Microsoft/perfview/blob/06b6969a40c1af70c437e6aca8cfb42b23e51db6/src/PerfView.Tests/StackViewer/StackWindowTests.cs#L107

**Screenshot from VS**
![image](https://user-images.githubusercontent.com/1007631/33146875-34700cf2-cfc6-11e7-9114-0569754fcb54.png)

**And this is how the GUI appear just before executing line 107** 
![image](https://user-images.githubusercontent.com/1007631/33146893-43496fac-cfc6-11e7-9b09-a45ed6884ae9.png)

**Comment by sharwell** [comment]
@mikkelbu I believe there is an exception getting thrown prior to reaching line 107. Can you use IntelliTrace or a separate copy of PerfView to record the behavior of this unit test so I can review it?

**Comment by mikkelbu** [comment]
@sharwell I don't have access to IntelliTrace. I've attached a log of all the CLR events - collected by PerfView - when I run the test from within VS (note that there are a lot of events since VS is always compiling the code before running the test). The full collected etl-zip is 30 MB, so I'll probably need some guidance if you want me to do a collection that is small enough for me to send to you. 

[CLR_Events.txt](https://github.com/Microsoft/perfview/files/1504237/CLR_Events.txt)

**Comment by vancem** [comment]
This tests also fails for me consistently locally.   I have been ignoring it meaning to get back to it.  

Now however  pull request #502 also fails this test in the debug build 
```
Executing: C:\Tools\xUnit20\xunit.console.x86.exe
xUnit.net Console Runner (32-bit .NET 4.0.30319.42000)
  Discovering: PerfViewTests (app domain = on [no shadow copy], method display = ClassAndMethod)
  Discovered:  PerfViewTests (running 13 test cases)
  Starting:    PerfViewTests (parallel test collections = on, max threads = 2)
    PerfViewTests.StackViewer.StackWindowTests.TestIncludeItemOnCallTreeTabAsync [PASS]
      Output:
        PerfView.TestUtilities.ThrowingTraceListener+DebugAssertFailureException: User did not call EndWork before returning from work body.
```
I am suggesting that he disable this test to work around the failure for now.  
I have recommended that

**Comment by sharwell** [comment]
@vancem I need the stack traces of first chance exceptions thrown while running that test when it fails.

> User did not call EndWork before returning from work body.

:arrow_up: AFAICT, this can only occur if an exception was thrown. Unfortunately I have no idea what or where it occurred.

**Comment by vancem** [comment]
Note that I don't actually get the assert locally, I get the IndexOutOfRange exception (however maybe that exception is causing the cascade error).

Here is where that

  System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index
   at System.ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument argument, ExceptionResource resource)
System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index
   at System.ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument argument, ExceptionResource resource)
   at System.Collections.Generic.List`1.System.Collections.IList.get_Item(Int32 index)
   at System.Windows.Data.ListCollectionView.InternalItemAt(Int32 index)
   at System.Windows.Data.ListCollectionView.GetItemAt(Int32 index)
   at System.Windows.Controls.ItemCollection.GetItemAt(Int32 index)
   at System.Windows.Controls.ItemCollection.get_Item(Int32 index)
   at PerfViewTests.StackViewer.StackWindowTests.<>c__DisplayClass8_0.<<TestIncludeItemAsync>b__2>d.MoveNext() in G:\repos\perfView\src\PerfView.Tests\StackViewer\StackWindowTests.cs:line 107
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index
   at System.ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument argument, ExceptionResource resource)
   at System.Collections.Generic.List`1.System.Collections.IList.get_Item(Int32 index)
   at System.Windows.Data.ListCollectionView.InternalItemAt(Int32 index)
   at System.Windows.Data.ListCollectionView.GetItemAt(Int32 index)
   at System.Windows.Controls.ItemCollection.GetItemAt(Int32 index)
   at System.Windows.Controls.ItemCollection.get_Item(Int32 index)
   at PerfViewTests.StackViewer.StackWindowTests.<>c__DisplayClass8_0.<<TestIncludeItemAsync>b__2>d.MoveNext() in G:\repos\perfView\src\PerfView.Tests\StackViewer\StackWindowTests.cs:line 107
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable.ConfiguredTaskAwaiter.GetResult()
   at PerfViewTests.Utilities.PerfViewTestBase.<>c__DisplayClass9_0`1.<<RunUITestAsync>b__1>d.MoveNext() in G:\repos\perfView\src\PerfView.Tests\Utilities\PerfViewTestBase.cs:line 72
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index
   at System.ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument argument, ExceptionResource resource)
   at System.Collections.Generic.List`1.System.Collections.IList.get_Item(Int32 index)
   at System.Windows.Data.ListCollectionView.InternalItemAt(Int32 index)
   at System.Windows.Data.ListCollectionView.GetItemAt(Int32 index)
   at System.Windows.Controls.ItemCollection.GetItemAt(Int32 index)
   at System.Windows.Controls.ItemCollection.get_Item(Int32 index)
   at PerfViewTests.StackViewer.StackWindowTests.<>c__DisplayClass8_0.<<TestIncludeItemAsync>b__2>d.MoveNext() in G:\repos\perfView\src\PerfView.Tests\StackViewer\StackWindowTests.cs:line 107
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable.ConfiguredTaskAwaiter.GetResult()
   at PerfViewTests.Utilities.PerfViewTestBase.<>c__DisplayClass9_0`1.<<RunUITestAsync>b__1>d.MoveNext() in G:\repos\perfView\src\PerfView.Tests\Utilities\PerfViewTestBase.cs:line 72
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at PerfViewTests.Utilities.PerfViewTestBase.<>c__DisplayClass9_0`1.<<RunUITestAsync>b__1>d.MoveNext() in G:\repos\perfView\src\PerfView.Tests\Utilities\PerfViewTestBase.cs:line 77
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
I have also captured a trace of running just this test at \clrmain\public\writable\users\vancem\PerfViewTestFailure.etl.zip

It shows an ArgumentOutOfRange exception at the line

 object selectedItem = dataGrid.Grid.Items[0];
This is what I see in the debugger as well. In the debugger the 'Items' list has a count of 0.

**Comment by sharwell** [comment]
I was finally able to reproduce this by enabling display scaling on the machine where tests are run.

**Comment by vancem** [comment]
Very good!.   With luck, it is easy from here...
