### ISSUE TITLE
latest perfview.exe fails to open DiagSession File on a machine which doesnt have VS 2015 installed

### ISSUE THREAD

**Issue by puneetg1983** [Microsoft/perfview#356]
Looks like a lot of project level changes happened and this error is back in the latest perfiview codebase from GITHUB

Started with command line: "E:\source\Perfview\src\PerfView\bin\Debug\net45\PerfView.exe" 
PerfView Version: 1.9.58.0  BuildDate: Mon, 21 Aug 2017 12:36:26 GMT
Started: View
Warning: PdbScope not found at E:\source\Perfview\src\PerfView\bin\Debug\net45\PerfViewExtensions\PdbScope.exe
Disabling the Image Size Menu Item.
Warning: ILSize not found at E:\source\Perfview\src\PerfView\bin\Debug\net45\PerfViewExtensions\ILSize.dll
Disabling the IL Size Menu Item.
Completed: View   (Elapsed Time: 0.095 sec)
Started: Opening KECHAW_SESSION_profile_59eb45_IISProfiling_w3wp_27572.diagsession
Opening diagnostics session file KECHAW_SESSION_profile_59eb45_IISProfiling_w3wp_27572.diagsession
Completed: Opening KECHAW_SESSION_profile_59eb45_IISProfiling_w3wp_27572.diagsession   (Elapsed Time: 0.081 sec)
Exception Occurred: System.ArgumentNullException: Value cannot be null.
Parameter name: pathToNativePackagingDll
   at Microsoft.DiagnosticsHub.Packaging.InteropEx.DhPackage.GetPackageFactory(String pathToNativePackagingDll)
   at Microsoft.DiagnosticsHub.Packaging.InteropEx.DhPackage.LoadAndOpen(String pathToPackage, String pathToPackageAssembly)
   at Microsoft.DiagnosticsHub.Packaging.InteropEx.DhPackage.Open(String pathToPackage)
   at PerfView.DiagSessionPerfViewFile.OpenImpl(Window parentWindow, StatusBar worker) in E:\source\perfview\src\PerfView\PerfViewData.cs:line 7302
   at PerfView.DiagSessionPerfViewFile.<>c__DisplayClass6_0.<Open>b__0() in E:\source\perfview\src\PerfView\PerfViewData.cs:line 7281
   at PerfView.StatusBar.<>c__DisplayClass19_0.<StartWork>b__0() in E:\source\perfview\src\PerfView\GuiUtilities\StatusBar\StatusBar.xaml.cs:line 230
An exceptional condition occurred, see log for details.

**Comment by vancem** [comment]
I should be able to start looking at this late today.  With luck it will be an easy fix.

**Comment by vancem** [comment]
Fixed by #361
