### ISSUE TITLE
Perfview heap dump of a big process causes System.OverflowException

### ISSUE THREAD

**Issue by kostteg** [Microsoft/perfview#398]
When I try to make a heap dump in Perfview of a rather big process (140+GB heap size) I get an Exception (possibly because of int32 overflow):

Process Has DotNet: True Has JScript: False Has ClrDll: True HasMrt False
*****  Attempting a .NET Heap Dump.
Enumerating over 1 detected runtimes...
/Freeze not present, skipping Debugger attach.
Creating Runtime access object for runtime v4.6.1586.00.
DumpDotNetHeapData: Heap Size 2 MB
Dumping GC heap, This process is a 64 bit process on a 64 bit OS
  0,3s: Starting heap dump 10.10.2017 10:42:50
  0,3s: Size of heap = 142,679 GB
In a 64 bit process.  Increasing the max node count to 134,2 Meg
Implicitly limit the number of nodes to 134,2 Meg to avoid arrays that are too large
Estimated number of objects = -2,065,600,157
HeapDump Error: System.OverflowException: Array dimensions exceeded supported range.
   at Graphs.Graph..ctor(Int32 expectedNodeCount)
   at Graphs.MemoryGraph..ctor(Int32 expectedSize)
   at GCHeapDumper.DumpDotNetHeapDataWorker(ClrHeap heap, ICorDebugProcess& debugProcess, Boolean isDump, Double retryScale)
   at GCHeapDumper.DumpDotNetHeapData(ClrHeap heap, ICorDebugProcess& debugProcess, Boolean isDump)
   at GCHeapDumper.TryGetDotNetDump(Int32 processID)
   at GCHeapDumper.CaptureLiveHeapDump(Int32 processID)
   at GCHeapDumper.DumpLiveHeap(Int32 processID)
   at Program.MainWorker(String[] args)

**Comment by krolth** [comment]
Got the same error (same callstack) on a Memory dump for a leaky service:

Dumping GC heap, This process is a 64 bit process on a 64 bit OS
  6.3s: Starting heap dump 12/31/2018 3:27:51 PM
  6.3s: Size of heap = 230.749 GB
In a 64 bit process.  Increasing the max node count to 134.2 Meg
Implicitly limit the number of nodes to 134.2 Meg to avoid arrays that are too large
Estimated number of objects = -689,519,657
HeapDump Error: System.OverflowException: Array dimensions exceeded supported range.

**Comment by brianrob** [comment]
As a starting point, it sounds like the answer here is to more aggressively sample the dump limit the size of the input to `Graph..ctor`.  It's probably also worth looking into what options we have to support increasing the max graph size, but I expect this to be a more invasive change.
