### ISSUE TITLE
In attempting to open an '.etl.zip' file with TraceLog, FileNotFound is thrown

### ISSUE THREAD

**Issue by nategraf** [microsoft/perfview#407]
In trying to create an etlx file from an etl.zip archive with the `TraceLog.CreateFromEventTraceLogFile` a `FileNotFoundException` is thrown for existing files

This is because [`TraceEventDispatcher`](https://github.com/Microsoft/perfview/blob/master/src/TraceEvent/TraceEvent.cs#L2716-L2717) accepts .etl.zip files, but when it gets to [`ETWTraceEventSource.GetMergeAllLogFiles`](https://github.com/Microsoft/perfview/blob/master/src/TraceEvent/ETWTraceEventSource.cs#L573-L586) via `ETWTraceEventSource.Initialize` there is not a case for .etl.zip files. 

If .etl.zip files are meant to be supported, it should be fixed so this exception is not raised. If they are not supported, the code should fail faster and raise a more helpful exception

Here is a stack trace from my program that triggered this error:
```
Unhandled Exception: System.IO.FileNotFoundException: Could not find file     E:\OneDrive\App Compat Traces\perfcollectdata\P0_Sub P0\Advanced Combat Tracker\AdvancedCombatTrackerTest01\AdvancedCombatTrackerTest01.etl.zip
   at Microsoft.Diagnostics.Tracing.ETWTraceEventSource.GetMergeAllLogFiles(String fileName) in E:\CPUStats\PerfView\TraceEvent\ETWTraceEventSource.cs:line 586
   at Microsoft.Diagnostics.Tracing.ETWTraceEventSource.Initialize(String fileOrSessionName, TraceEventSourceType type) in E:\CPUStats\PerfView\TraceEvent\ETWTraceEventSource.cs:line 355
   at Microsoft.Diagnostics.Tracing.TraceEventDispatcher.GetDispatcherFromFileName(String traceFileName) in E:\CPUStats\PerfView\TraceEvent\TraceEvent.cs:line 2714
   at Microsoft.Diagnostics.Tracing.Etlx.TraceLog.CreateFromEventTraceLogFile(String filePath, String etlxFilePath, TraceLogOptions options) in E:\CPUStats\PerfView\TraceEvent\TraceLog.cs:line 63
   at CPUStats.CPUStats.ComputeStats() in E:\CPUStats\CPUStats.cs:line 489
   at CPUStats.Program.Main(String[] args) in E:\CPUStats\Program.cs:line 56
```

**Comment by brianrob** [comment]
This path is not expected to work with an etl.zip file.  The contents of the zip file are expected to extracted first.
