### ISSUE TITLE
OutOfMemoryException thrown when opening the 'Thread Time (with ReadyThread) stacks' view

### ISSUE THREAD

**Issue by GearedToWar** [microsoft/perfview#409]
I can open the 'Thread Time Stacks' view successfully.
Opening the 'Thread Time (with Tasks) Stacks' view also fails with the same error.

From the status log -
```
Exception Occurred: System.OutOfMemoryException: Exception of type 'System.OutOfMemoryException' was thrown.
   at Microsoft.Diagnostics.Tracing.Stacks.StackSourceInterner.InternTable`1.Resize(Int32 desiredSize)
   at Microsoft.Diagnostics.Tracing.Stacks.StackSourceInterner.InternTable`1.Intern(T value)
   at Microsoft.Diagnostics.Tracing.Stacks.StackSourceInterner.CallStackIntern(StackSourceFrameIndex frameIndex, StackSourceCallStackIndex callerIndex)
   at Microsoft.Diagnostics.Tracing.ThreadTimeStackComputer.GenerateReadyThreadNodes(MutableTraceEventStackSource stackSource, StackSourceCallStackIndex stackIndex, CallStackIndex readyThreadCallStack, Double msecWaitingForCpu, Int32 idleCPUs)
   at Microsoft.Diagnostics.Tracing.ThreadTimeStackComputer.GenerateReadyThreadNodes(MutableTraceEventStackSource stackSource, StackSourceCallStackIndex stackIndex, CallStackIndex readyThreadCallStack, Double msecWaitingForCpu, Int32 idleCPUs)
   at Microsoft.Diagnostics.Tracing.ThreadTimeStackComputer.GenerateReadyThreadNodes(MutableTraceEventStackSource stackSource, StackSourceCallStackIndex stackIndex, CallStackIndex readyThreadCallStack, Double msecWaitingForCpu, Int32 idleCPUs)
   at Microsoft.Diagnostics.Tracing.ThreadTimeStackComputer.GenerateReadyThreadNodes(MutableTraceEventStackSource stackSource, StackSourceCallStackIndex stackIndex, CallStackIndex readyThreadCallStack, Double msecWaitingForCpu, Int32 idleCPUs)
   at Microsoft.Diagnostics.Tracing.ThreadTimeStackComputer.GenerateReadyThreadNodes(MutableTraceEventStackSource stackSource, StackSourceCallStackIndex stackIndex, CallStackIndex readyThreadCallStack, Double msecWaitingForCpu, Int32 idleCPUs)
   at Microsoft.Diagnostics.Tracing.ThreadTimeStackComputer.GenerateReadyThreadNodes(MutableTraceEventStackSource stackSource, StackSourceCallStackIndex stackIndex, CallStackIndex readyThreadCallStack, Double msecWaitingForCpu, Int32 idleCPUs)
   at Microsoft.Diagnostics.Tracing.ThreadTimeStackComputer.GenerateReadyThreadNodes(MutableTraceEventStackSource stackSource, StackSourceCallStackIndex stackIndex, CallStackIndex readyThreadCallStack, Double msecWaitingForCpu, Int32 idleCPUs)
   at Microsoft.Diagnostics.Tracing.ThreadTimeStackComputer.GenerateReadyThreadNodes(MutableTraceEventStackSource stackSource, StackSourceCallStackIndex stackIndex, CallStackIndex readyThreadCallStack, Double msecWaitingForCpu, Int32 idleCPUs)
   at Microsoft.Diagnostics.Tracing.ThreadTimeStackComputer.GenerateReadyThreadNodes(MutableTraceEventStackSource stackSource, StackSourceCallStackIndex stackIndex, CallStackIndex readyThreadCallStack, Double msecWaitingForCpu, Int32 idleCPUs)
   at Microsoft.Diagnostics.Tracing.ThreadTimeStackComputer.GenerateReadyThreadNodes(MutableTraceEventStackSource stackSource, StackSourceCallStackIndex stackIndex, CallStackIndex readyThreadCallStack, Double msecWaitingForCpu, Int32 idleCPUs)
   at Microsoft.Diagnostics.Tracing.ThreadTimeStackComputer.GenerateReadyThreadNodes(MutableTraceEventStackSource stackSource, StackSourceCallStackIndex stackIndex, CallStackIndex readyThreadCallStack, Double msecWaitingForCpu, Int32 idleCPUs)
   at Microsoft.Diagnostics.Tracing.ThreadTimeStackComputer.GenerateReadyThreadNodes(MutableTraceEventStackSource stackSource, StackSourceCallStackIndex stackIndex, CallStackIndex readyThreadCallStack, Double msecWaitingForCpu, Int32 idleCPUs)
   at Microsoft.Diagnostics.Tracing.ThreadTimeStackComputer.GenerateReadyThreadNodes(MutableTraceEventStackSource stackSource, StackSourceCallStackIndex stackIndex, CallStackIndex readyThreadCallStack, Double msecWaitingForCpu, Int32 idleCPUs)
   at Microsoft.Diagnostics.Tracing.ThreadTimeStackComputer.GenerateReadyThreadNodes(MutableTraceEventStackSource stackSource, StackSourceCallStackIndex stackIndex, CallStackIndex readyThreadCallStack, Double msecWaitingForCpu, Int32 idleCPUs)
   at Microsoft.Diagnostics.Tracing.ThreadTimeStackComputer.GenerateReadyThreadNodes(MutableTraceEventStackSource stackSource, StackSourceCallStackIndex stackIndex, CallStackIndex readyThreadCallStack, Double msecWaitingForCpu, Int32 idleCPUs)
   at Microsoft.Diagnostics.Tracing.ThreadTimeStackComputer.GenerateReadyThreadNodes(MutableTraceEventStackSource stackSource, StackSourceCallStackIndex stackIndex, CallStackIndex readyThreadCallStack, Double msecWaitingForCpu, Int32 idleCPUs)
   at Microsoft.Diagnostics.Tracing.ThreadTimeStackComputer.GenerateReadyThreadNodes(MutableTraceEventStackSource stackSource, StackSourceCallStackIndex stackIndex, CallStackIndex readyThreadCallStack, Double msecWaitingForCpu, Int32 idleCPUs)
   at Microsoft.Diagnostics.Tracing.ThreadTimeStackComputer.GenerateReadyThreadNodes(MutableTraceEventStackSource stackSource, StackSourceCallStackIndex stackIndex, CallStackIndex readyThreadCallStack, Double msecWaitingForCpu, Int32 idleCPUs)
   at Microsoft.Diagnostics.Tracing.ThreadTimeStackComputer.GenerateReadyThreadNodes(MutableTraceEventStackSource stackSource, StackSourceCallStackIndex stackIndex, CallStackIndex readyThreadCallStack, Double msecWaitingForCpu, Int32 idleCPUs)
   at Microsoft.Diagnostics.Tracing.ThreadTimeStackComputer.GenerateReadyThreadNodes(MutableTraceEventStackSource stackSource, StackSourceCallStackIndex stackIndex, CallStackIndex readyThreadCallStack, Double msecWaitingForCpu, Int32 idleCPUs)
   at Microsoft.Diagnostics.Tracing.ThreadTimeStackComputer.GenerateReadyThreadNodes(MutableTraceEventStackSource stackSource, StackSourceCallStackIndex stackIndex, CallStackIndex readyThreadCallStack, Double msecWaitingForCpu, Int32 idleCPUs)
   at Microsoft.Diagnostics.Tracing.ThreadTimeStackComputer.GenerateReadyThreadNodes(MutableTraceEventStackSource stackSource, StackSourceCallStackIndex stackIndex, CallStackIndex readyThreadCallStack, Double msecWaitingForCpu, Int32 idleCPUs)
   at Microsoft.Diagnostics.Tracing.ThreadTimeStackComputer.GenerateReadyThreadNodes(MutableTraceEventStackSource stackSource, StackSourceCallStackIndex stackIndex, CallStackIndex readyThreadCallStack, Double msecWaitingForCpu, Int32 idleCPUs)
   at Microsoft.Diagnostics.Tracing.ThreadTimeStackComputer.GenerateReadyThreadNodes(MutableTraceEventStackSource stackSource, StackSourceCallStackIndex stackIndex, CallStackIndex readyThreadCallStack, Double msecWaitingForCpu, Int32 idleCPUs)
   at Microsoft.Diagnostics.Tracing.ThreadTimeStackComputer.GenerateReadyThreadNodes(MutableTraceEventStackSource stackSource, StackSourceCallStackIndex stackIndex, CallStackIndex readyThreadCallStack, Double msecWaitingForCpu, Int32 idleCPUs)
   at Microsoft.Diagnostics.Tracing.ThreadTimeStackComputer.GenerateReadyThreadNodes(MutableTraceEventStackSource stackSource, StackSourceCallStackIndex stackIndex, CallStackIndex readyThreadCallStack, Double msecWaitingForCpu, Int32 idleCPUs)
   at Microsoft.Diagnostics.Tracing.ThreadTimeStackComputer.GenerateReadyThreadNodes(MutableTraceEventStackSource stackSource, StackSourceCallStackIndex stackIndex, CallStackIndex readyThreadCallStack, Double msecWaitingForCpu, Int32 idleCPUs)
   at Microsoft.Diagnostics.Tracing.ThreadTimeStackComputer.GenerateReadyThreadNodes(MutableTraceEventStackSource stackSource, StackSourceCallStackIndex stackIndex, CallStackIndex readyThreadCallStack, Double msecWaitingForCpu, Int32 idleCPUs)
   at Microsoft.Diagnostics.Tracing.ThreadTimeStackComputer.ThreadState.LogBlockingEnd(Double timeRelativeMSec, Int32 processorNumber, StackSourceCallStackIndex stackIndex, TraceThread thread, ThreadTimeStackComputer computer)
   at Microsoft.Diagnostics.Tracing.ThreadTimeStackComputer.OnThreadCSwitch(CSwitchTraceData data)
   at Microsoft.Diagnostics.Tracing.Parsers.Kernel.CSwitchTraceData.Dispatch()
   at Microsoft.Diagnostics.Tracing.TraceEventDispatcher.Dispatch(TraceEvent anEvent)
   at Microsoft.Diagnostics.Tracing.Etlx.TraceLogEventSource.Process()
   at Microsoft.Diagnostics.Tracing.ThreadTimeStackComputer.GenerateThreadTimeStacks(MutableTraceEventStackSource outputStackSource, TraceEvents traceEvents)
   at TraceEventStackSourceExtensions.ThreadTimeWithReadyThreadStacks(TraceLog eventLog, TraceProcess process, Boolean showUnknownAddresses)
   at PerfView.ETLPerfViewData.OpenStackSourceImpl(String streamName, TextWriter log, Double startRelativeMSec, Double endRelativeMSec, Predicate`1 predicate)
   at PerfView.PerfViewStackSource.OpenStackSource(String streamName, TextWriter log, Double startRelativeMSec, Double endRelativeMSec, Predicate`1 predicate)
   at PerfView.PerfViewStackSource.<>c__DisplayClass23_0.<Open>b__0()
   at PerfView.StatusBar.<>c__DisplayClass18_0.<StartWork>b__0()
```

**Comment by sharwell** [comment]
It sounds like you need to run **PerfView64.exe** instead of **PerfView.exe** in order to open the trace.

**Comment by GearedToWar** [comment]
Thanks @sharwell. I'll give that a try.

**Comment by brianrob** [comment]
Hopefully Perfview64 resolved this.  If this is still an issue, please do re-open.  We'd also need a repro file to make progress here.  Thanks.
