### ISSUE TITLE
AccessViolationException With PerfView64.exe

### ISSUE THREAD

**Issue by shortspider** [microsoft/perfview#524]
I am running the following command on my windows 10 machine and consistently get an access violation exception:

`.\PerfView64.exe collect -AcceptEULA -NoView -LogFile:log.txt -CircularMB:1000 -KernelEvents:Handle,Default -Providers:"ClrStress" -StopOnEventLogMessage:"Faulting application name" collection.etl`

If I use `PerfView.exe` instead of `PerfView64.exe` it works fine.

The full callstack is:

```
Pre V4.0 .NET Rundown enabled, Type 'D' to disable and speed up .NET Rundown.
Do NOT close this console window.   It will leave collection on!
Type S to stop collection, 'A' will abort.  (Also consider /MaxCollectSec:N)

Unhandled Exception: System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
   at System.Security.SecurityRuntime.GetSecurityObjectForFrame(StackCrawlMark& stackMark, Boolean create)
   at System.Security.SecurityRuntime.RevertAssert(StackCrawlMark& stackMark)
   at System.Security.CodeAccessPermission.RevertAssert()
   at System.Diagnostics.EventLog.Exists(String logName, String machineName)
   at System.Diagnostics.EventLogInternal.OpenForRead(String currentMachineName)
   at System.Diagnostics.EventLogInternal.get_EntryCount()
   at System.Diagnostics.EventLogInternal.StartListening(String currentMachineName, String currentLogName)
   at System.Diagnostics.EventLogInternal.StartRaisingEvents(String currentMachineName, String currentLogName)
   at System.Diagnostics.EventLogInternal.set_EnableRaisingEvents(Boolean value)
   at PerfView.CommandProcessor.WaitUntilCollectionDone(ManualResetEvent collectionCompleted, CommandLineArgs parsedArgs, DateTime startTime)
   at PerfView.CommandProcessor.Collect(CommandLineArgs parsedArgs)
   at PerfView.CommandProcessor.ExecuteCommand(CommandLineArgs parsedArgs)
   at PerfView.App.DoMain(String[] args, Boolean& newConsoleCreated, StreamWriter& textWriterToCleanUp)
   at PerfView.App.Main(String[] args)
   at PerfView64.App.Main(String[] args)

```

The log file contents are:

```
PerfView logging started at 15-Jan-18 3:52:33 PM
[EXECUTING: PerfView collect -AcceptEULA -NoView -LogFile:log.txt -CircularMB:1000 -KernelEvents:Handle,Default -Providers:ClrStress -StopOnEventLogMessage:Faulting application name collection.etl]
[Kernel Log: C:\Users\ME\Desktop\perfview\collection.kernel.etl]
Kernel keywords enabled: Handle, Default
[User mode Log: C:\Users\ME\Desktop\perfview\collection.etl]
Enabling Provider:PerfViewLogger Level:Verbose Keywords:0xffffffffffffffff Stacks:0 Values: Guid:a8a71ac1-040f-54a2-07ca-00a89b5ab761
Turning on more CLR GC, JScript and ASP.NET Events.
Enabling Provider:DotNet Level:Verbose Keywords:0xffffffffffffffff Stacks:1 Values: Guid:319dc449-ada5-50f7-428e-957db6791668
Enabling Provider:Microsoft-Windows-Kernel-EventTracing Level:Verbose Keywords:0x70 Stacks:1 Values: Guid:b675ec37-bdb6-4648-bc92-f3fdc74d3ca2
Enabling Provider:Microsoft-Windows-Kernel-Process Level:Informational Keywords:0x10 Stacks:1 Values: Guid:22fb2cd6-0e7b-422b-a0c7-2fad1fd0e716
Enabling Provider:Microsoft-Windows-Kernel-File Level:Verbose Keywords:0x80 Stacks:1 Values: Guid:edd08927-9cc4-4e65-b970-c2560fb5c289
Enabling Provider:ASP.NET Level:Verbose Keywords:0xfffffffffffffffd Stacks:0 Values: Guid:aff081fe-0247-4275-9c4e-021f3dc1da35
File C:\WINDOWS\System32\inetsrv\iiscore.dll does not, ASP.NET is not enabled on the machine
Enabling Provider:*Microsoft-Windows-ASPNET Level:Informational Keywords:0xffffffffffffffff Stacks:1 Values: Guid:ee799f41-cfa5-550b-bf2c-344747c1c668
Enabling Provider:Microsoft-Windows-IIS Level:Critical Keywords:0x0 Stacks:0 Values: Guid:de4649c9-15e8-4fea-9d85-1cdda520c334
Enabling Provider:Microsoft-PerfTrack-IEFRAME Level:Verbose Keywords:0xffffffffffffffff Stacks:0 Values: Guid:b2a40f1f-a05a-4dfd-886a-4c4f18c4334c
Enabling Provider:Microsoft-PerfTrack-MSHTML Level:Verbose Keywords:0xffffffffffffffff Stacks:0 Values: Guid:ffdb9886-80f3-4540-aa8b-b85192217ddf
Enabling Provider:Microsoft-Windows-WinINet Level:Verbose Keywords:0x2 Stacks:0 Values: Guid:43d1a55c-76d6-4f7e-995c-64c711e5cafe
Enabling Provider:Microsoft-Windows-Application Server-Applications Level:Informational Keywords:0xffffffffffffffff Stacks:0 Values: Guid:c651f5f6-1c0d-492e-8ae1-b4efd7c9d503
Enabling Provider:Microsoft-IE Level:Informational Keywords:0x1300 Stacks:0 Values: Guid:9e3b3947-ca5d-4614-91a2-7b624e0e7244
Enabling Provider:Microsoft-Windows-DNS-Client Level:Informational Keywords:0xffffffffffffffff Stacks:0 Values: Guid:1c95126e-7eea-49a9-a3fe-a378b03ddb4d
Enabling Provider:Microsoft-Windows-DirectComposition Level:Verbose Keywords:0x4 Stacks:0 Values: Guid:c44219d0-f344-11df-a5e2-b307dfd72085
Enabling Provider:Microsoft-Windows-Immersive-Shell Level:Informational Keywords:0xffffffffffffffff Stacks:0 Values: Guid:315a8872-923e-4ea2-9889-33cd4754bf64
Enabling Provider:Microsoft-Windows-XAML Level:Informational Keywords:0xffffffffffffffff Stacks:0 Values: Guid:531a35ab-63ce-4bcf-aa98-f88c7a89e455
Enabling Provider:Microsoft-JScript Level:Verbose Keywords:0xffffffffffffffff Stacks:0 Values: Guid:57277741-3638-4a4b-bdba-0ac6e45da56c
Enabling Provider:ClrPrivateNative Level:Informational Keywords:0x4002000b Stacks:0 Values: Guid:1095638c-8748-4c7a-b39e-baea27b9c589
Enabling Provider:CLRPrivate Level:Informational Keywords:0x4002000b Stacks:0 Values: Guid:763fd754-7086-4dfe-95eb-c01a46faf4ca
Enabling Provider:.NETTasks Level:Verbose Keywords:0xff Stacks:0 Values: Guid:2e5dba47-a3d2-4d16-8ee0-6671ffdcd7b5
Enabling Provider:.NETFramework Level:Verbose Keywords:0x16 Stacks:1 Values: Guid:8e9f5090-2d75-4d03-8a81-e5afbf85daf1
Enabling Provider:Microsoft.Tasks.Nuget Level:Informational Keywords:0x80 Stacks:0 Values: Guid:b734069e-103c-5376-2080-4f009207881a
Enabling Provider:Microsoft-AdoNet-SystemData Level:Informational Keywords:0x1 Stacks:1 Values: Guid:6a4dfe53-eb50-5332-8473-7b7e10a94fd1
Enabling Provider:ETWCLrProfiler Diagnostics Level:Verbose Keywords:0xffffffffffffffff Stacks:0 Values: Guid:6652970f-1756-5d8d-0805-e9aad152aa79
Enabling Provider:Microsoft-Diagnostics-DiagnosticSource Level:Informational Keywords:0xfffffffffffff7ff Stacks:1 Values:FilterAndPayloadSpecs=HttpHandlerDiagnosticListener/System.Net.Http.Request@Activity2Start:Request.RequestUri
HttpHandlerDiagnosticListener/System.Net.Http.Response@Activity2Stop:Response.StatusCode Guid:adb401e1-5296-51f8-c125-5fda75826144
Enabling Provider:Microsoft-ApplicationInsights-Core Level:Verbose Keywords:0xffffffffffffffff Stacks:1 Values: Guid:74af9f20-af6a-5582-9382-f21f674fb271
Enabling Provider:Microsoft-Windows-Kernel-Power Level:Informational Keywords:0xffb Stacks:0 Values: Guid:331c3b3a-2005-44c2-ac5e-77220c37d6b4
Enabling Provider:Microsoft-Windows-Kernel-Processor-Power Level:Informational Keywords:0xe5d Stacks:0 Values: Guid:0f67e49f-fe51-4e9f-b490-6f2948cc6027
Enabling Provider:Microsoft-Windows-PowerCpl Level:Informational Keywords:0xffffffffffffffff Stacks:0 Values: Guid:b1f90b27-4551-49d6-b2bd-dfc6453762a6
Enabling Provider:Microsoft-Windows-PowerCfg Level:Informational Keywords:0xffffffffffffffff Stacks:0 Values: Guid:9f0c4ea8-ec01-4200-a00d-b9701cbea5d8
Turning on VS CodeMarkers and MeasurementBlock Providers.
Enabling Provider:MeasurementBlock Level:Verbose Keywords:0xffffffffffffffff Stacks:0 Values: Guid:143a31db-0372-40b6-b8f1-b4b16adb5f54
Enabling Provider:CodeMarkers Level:Verbose Keywords:0xffffffffffffffff Stacks:0 Values: Guid:641d7f6c-481c-42e8-ab7e-d18dc5e5cb9e
Enabling CLR Events: Default
Enabling Provider:ClrNative Level:Verbose Keywords:0x4c14fccbd Stacks:1 Values: Guid:47c3ba0c-77f1-4eb0-8d4d-aef447f16a85
Enabling Provider:CLR Level:Verbose Keywords:0x4c14fccbd Stacks:0 Values: Guid:e13c0d23-ccbc-4e12-931b-d9cc2eee27e4
Enabling Providers specified by the user.
Parsing ETW Provider Spec: ClrStress
Enabling Provider:ClrStress Level:Verbose Keywords:0xffffffffffffffff Stacks:0 Values: Guid:cc2bcbba-16b6-4cf3-8990-d74c2e8af500
[Enabling StopOnEventLogMessage with Regex pattern: 'Faulting application name'.]
Using event log Application
```
If I used the GUI launched from PerfView64.exe and select the same options everything works fine. Any ideas? I can reproduce at will if you need more info.

EDIT: Forgot to mention I am using PerfView version 2.0.2.0.

**Comment by vancem** [comment]
I can repro this.  It actually looks like either a memory corruption issue or a bug in the .NET runtime.   

There is an obvious work around (you never have to use PerfVIew64.exe for collection).

**Comment by shortspider** [comment]
@vancem fair enough just wanted to report it. Any idea on why from the GUI it works but from the command line it doesn't?

**Comment by brianrob** [comment]
This does not repro for me on .NET 4.8.  I suspect that this was a bug in the .NET runtime as @vancem states above.
