### ISSUE TITLE
Unhandled Exception - NullReferenceException - PerfView.PerfViewStackSource

### ISSUE THREAD

**Issue by daviburg** [microsoft/perfview#641]
StackTrace:
System.NullReferenceException: Object reference not set to an instance of an object.
   at PerfView.PerfViewStackSource.<>c__DisplayClass23_4.<Open>b__6()
   at PerfView.StatusBar.<>c__DisplayClass23_0.<EndWork>b__0()
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by daviburg** [comment]
This issue happens when closing the window "Processes / Files / Registry Stack" after doing nothing but opening the same.

**Comment by vancem** [comment]
I would need the ETL.ZIP file that you opened which failed.   There is something special about your trace that triggers this (I can open this view fine on several ETL.ZIP files H have here...

**Comment by brianrob** [comment]
Per @vancem's comment, a repro is required for this.  Closing.
