### ISSUE TITLE
IndexOutOfRangeException when opening dump file

### ISSUE THREAD

**Issue by greg84** [microsoft/perfview#647]
Is this because the dump file has no heap data?

Here is the error:
```
********** TRYING TO OPEN THE DUMP AS 64 BIT ************
set _NT_SYMBOL_PATH=;SRV*C:\Users\Greg\AppData\Local\Temp\symbols*http://msdl.microsoft.com/download/symbols;SRV*C:\Users\Greg\AppData\Local\Temp\symbols*https://nuget.smbsrc.net;SRV*C:\Users\Greg\AppData\Local\Temp\symbols*http://referencesource.microsoft.com/symbols;SRV*C:\Users\Greg\AppData\Local\Temp\symbols*https://dotnet.myget.org/F/dotnet-core/symbols
Exec: "C:\Users\Greg\AppData\Roaming\PerfView\VER.2018-04-30.10.59.59.025\amd64\HeapDump.exe" /processDump  /MaxDumpCountK=250 "C:\Users\Greg\Downloads\dump.dmp" "C:\Users\Greg\Downloads\dump.gcdump"
Creating heap dump C:\Users\Greg\Downloads\dump.gcdump from process dump C:\Users\Greg\Downloads\dump.dmp.
Enumerating over 1 detected runtimes...
Created SymbolReader with SymbolPath ;SRV*C:\Users\Greg\AppData\Local\Temp\symbols*http://msdl.microsoft.com/download/symbols;SRV*C:\Users\Greg\AppData\Local\Temp\symbols*https://nuget.smbsrc.net;SRV*C:\Users\Greg\AppData\Local\Temp\symbols*http://referencesource.microsoft.com/symbols;SRV*C:\Users\Greg\AppData\Local\Temp\symbols*https://dotnet.myget.org/F/dotnet-core/symbols
Creating Runtime access object for runtime v4.7.2563.00.
Creating a GC Dump from the dump file C:\Users\Greg\Downloads\dump.dmp
Trying to get a ICorDebugProcess object.
DumpDotNetHeapData: Heap Size 7 MB
Dumping GC heap, This process is a 64 bit process on a 64 bit OS
  3.0s: Starting heap dump 30/04/2018 11:12:42
  3.0s: Size of heap = 0.000 GB
In a 64 bit process.  Increasing the max node count to 134.2 Meg
Implicitly limit the number of nodes to 134.2 Meg to avoid arrays that are too large
Estimated number of objects = 0
HeapDump Error: System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at FastSerialization.MemoryStreamWriter.Write(Byte value)
   at Graphs.Graph.SetNode(NodeIndex nodeIndex, NodeTypeIndex typeIndex, Int32 sizeInBytes, GrowableArray`1 children)
   at Graphs.Graph.ClearWorker()
   at Graphs.MemoryGraph..ctor(Int32 expectedSize)
   at GCHeapDumper.DumpDotNetHeapDataWorker(ClrHeap heap, ICorDebugProcess& debugProcess, Boolean isDump, Double retryScale)
   at GCHeapDumper.DumpDotNetHeapData(ClrHeap heap, ICorDebugProcess& debugProcess, Boolean isDump)
   at GCHeapDumper.DumpHeapFromProcessDump(String processDumpFile)
   at Program.MainWorker(String[] args)
```

**Comment by vancem** [comment]
This is clearly a bug, but I really can't fix it without a repro.   If you can provide the dump.dmp file (you can e-mail me some link to vancem@microsoft.com), I should be able to fix it.

**Comment by brianrob** [comment]
Per @vancem's comment, this will require a repro.  Closing.
