### ISSUE TITLE
outofmemoryerror with large heap dump

### ISSUE THREAD

**Issue by jmunty** [microsoft/perfview#721]
Hi

I have a heap dump file that i'm trying to convert into perfview format gcdump. 

the heap dump file is 3.6 GB

The error message is as follows:

> Sampled Graph node count     252ÿ151 (reduced by 228,80 ratio)
> Sampled Graph type count         537 (reduced by 29,42 ratio)
> Sampled Graph node size  166ÿ074ÿ245 (reduced by 12,06 ratio)
> 401,2s:   Done Sampling.
> Average Count Multiplier: 228,80
> Average Size Multiplier:   12,06
> After sampling Object Count 252151K    Total GC Heap Size 166,1 MB 
> Dump Created from a .DMP file, no live statistics
> The process being dumped is 32 Bit
> Actual number of objects dumped = 252ÿ151
> Actual number of types = 537
> Size of dumped objects 166,1 MB
> HeapDump Error: System.OutOfMemoryException: Exception of type 'System.OutOfMemoryException' was thrown.
>    at System.Text.StringBuilder.ToString()
>    at System.IO.StringWriter.ToString()
>    at GCHeapDumper.WriteData(Boolean logLiveStats)
>    at GCHeapDumper.DumpHeapFromProcessDump(String processDumpFile)
>    at Program.MainWorker(String[] args)

I'm using 64bit perfview: 
![image](https://user-images.githubusercontent.com/18736993/43724263-d2a3b3c2-9999-11e8-8652-a960258ae74e.png)

at the time of crash i've got approx 10GB free physical mem on my machine

![image](https://user-images.githubusercontent.com/18736993/43724250-cbf879ea-9999-11e8-955a-caa1ac5252bd.png)

Any tips on what i should do here?

**Comment by jmunty** [comment]
also built from source (as i was worried it might be something with my antivirus)
but got the same error

build info: 
![image](https://user-images.githubusercontent.com/18736993/43759579-eb286042-9a1f-11e8-8016-0756b4ef8509.png)

will try running another session of perfview to see what the problem is here...

**Comment by jmunty** [comment]
tried opening with windbg and get an error... so may be a problem with the dump file (from dbgdiag)

> 0:000> !DumpHeap -stat
> The garbage collector data structures are not in a valid state for traversal.
> It is either in the "plan phase," where objects are being moved around, or
> we are at the initialization or shutdown of the gc heap. Commands related to 
> displaying, finding or traversing objects as well as gc heap segments may not 
> work properly. !dumpheap and !verifyheap may incorrectly complain of heap 
> consistency errors.
> Object <exec cmd="!ListNearObj /d 02261000">02261000</exec> has an invalid method table.

will test with some other dump files

**Comment by brianrob** [comment]
@jmunty, is this still an issue?
