### ISSUE TITLE
System.ArgumentException on starting hardware counter session

### ISSUE THREAD

**Issue by kkokosa** [Microsoft/perfview#735]
I am unable to create hardware-based session, because `EnableKernelProvider` throws `System.ArgumentException`. Simple example:

```   
class Program
{
    static void Main(string[] args)
    {
        var infos = TraceEventProfileSources.GetInfo();
        TraceEventProfileSources.Set(infos["BranchInstructions"].ID, infos["BranchInstructions"].Interval);
        var session = new TraceEventSession(KernelTraceEventParser.KernelSessionName);
        session.EnableKernelProvider(KernelTraceEventParser.Keywords.PMCProfile |
                                     KernelTraceEventParser.Keywords.Profile);

        session.Source.Kernel.PerfInfoCollectionStart += _ => { }; // we must subscribe to this event, otherwise the PerfInfoPMCSample is not raised ;)
        session.Source.Kernel.PerfInfoPMCSample += OnPerfInfoPmcSample;
    }
    private static void OnPerfInfoPmcSample(PMCCounterProfTraceData obj)
    {            
    }
}
```

The exception:

```
{System.ArgumentException: Value does not fall within the expected range.
   at System.Runtime.InteropServices.Marshal.ThrowExceptionForHRInternal(Int32 errorCode, IntPtr errorInfo)
   at Microsoft.Diagnostics.Tracing.Session.TraceEventSession.EnableKernelProvider(Keywords flags, Keywords stackCapture) in F:\GithubProjects\perfview\src\TraceEvent\TraceEventSession.cs:line 717
   at ConsoleApp1.Program.Main(String[] args) in F:\GithubProjects\perfview\ConsoleApp1\Program.cs:line 15}
```

This happens in a simple console app that I've added to perfview solution, referencing freshly built TraceEvent library. But the same happens with TraceEvent from Nuget and even with TraceEvent used by BenchmarkDotNet. The same happens also on my second computer...

What I see is that underlying `ETWKernelControl.StartTraceW` returns 0x57 but I completely have no clue how to debug it further.

**Comment by adamsitnik** [comment]
@kkokosa what is the `.Interval` returning? Could you try `.MaxInterval` instead?

**Comment by kkokosa** [comment]
@adamsitnik the same exception with `.MaxInterval`. Values:

```
infos["BranchInstructions"].Interval
65536
infos["BranchInstructions"].MaxInterval
2147483647
infos["BranchInstructions"].MinInterval
4096
```

**Comment by adamsitnik** [comment]
@kkokosa I was able to reproduce because I have hit exactly the same issue today ;)

Works with TraceEvent `1.0.41`, fails since `2.0.2`

**Comment by adamsitnik** [comment]
@kkokosa I have found the source of the bug in the closed-source `OSExtensions.dll` I will start internal MS conversation from here to get it fixed and let you know once we have a fix

**Comment by kkokosa** [comment]
@adamsitnik great, thank you!
