### ISSUE TITLE
0x8007007A and 0x80070005 

### ISSUE THREAD

**Issue by axelgMS** [Microsoft/perfview#794]
Hey there,

Azure IaaS VM Guest Agent is using some of your Diagnostics.Tracing code and we're seeing exceptions below in few VMs:

[00000011] [08/21/2018 05:55:56.86] [INFO]  Session filename is 'C:\WindowsAzure\Logs\WindowsAzure-GuestAgent-Metrics_2018_8_21_5_50_56.etl'
[00000011] [08/21/2018 05:55:56.86] [ERROR] Failed to process metrics file because of System.Runtime.InteropServices.COMException (0x8007007A): The data area passed to a system call is too small. (Exception from HRESULT: 0x8007007A)
   at System.Runtime.InteropServices.Marshal.ThrowExceptionForHRInternal(Int32 errorCode, IntPtr errorInfo)
   at Diagnostics.Tracing.TraceEventSession.GetRegisteredOrEnabledProviders()
   at Diagnostics.Tracing.TraceEventSession.CleanFilterDataForEtwSession()
   at Diagnostics.Tracing.TraceEventSession.Stop(Boolean noThrow)
   at Microsoft.WindowsAzure.GuestAgent.Telemetry.TraceSession.StopSession()

[00000011] [08/23/2018 22:46:00.59] [INFO]  Session filename is 'C:\WindowsAzure\Logs\WindowsAzure-GuestAgent-Metrics_2018_8_21_5_50_56.etl'
[00000011] [08/23/2018 22:46:00.59] [ERROR] Failed to process metrics file because of System.UnauthorizedAccessException: Access is denied. (Exception from HRESULT: 0x80070005 (E_ACCESSDENIED))
   at System.Runtime.InteropServices.Marshal.ThrowExceptionForHRInternal(Int32 errorCode, IntPtr errorInfo)
   at Diagnostics.Tracing.ETWTraceEventSource.Initialize(String fileOrSessionName, TraceEventSourceType type)
   at Microsoft.WindowsAzure.GuestAgent.Telemetry.TraceSession.Open(TraceEventSourceType sourceType)

Any ideas what's causing these 0x8007007A and 0x80070005 ?

err 0x8007007A
as an HRESULT: Severity: FAILURE (1), FACILITY_WIN32 (0x7), Code 0x7a
 for hex 0x7a / decimal 122
  ERROR_INSUFFICIENT_BUFFER                                      winerror.h
 The data area passed to a system call is too small.

 for hex 0x80070005 / decimal -2147024891
  COR_E_UNAUTHORIZEDACCESS                                       corerror.h
 Access is denied.
 General access denied error
 as an HRESULT: Severity: FAILURE (1), FACILITY_WIN32 (0x7), Code 0x5
 for hex 0x5 / decimal 5
  ERROR_ACCESS_DENIED                                            winerror.h
 Access is denied.

thanks

**Comment by axelgMS** [comment]
thanks Vance.
Yes, I overlooked code quite fast and just check the GetRegisteredOrEnabledProviders() which was very close to yours, but you're right, other parts of the code are different - especially the CleanFilterDataForEtwSession(). I'll see with our team if they can upgrade

For the Access Denied, our Guest Agent runs as LocalSystem - so it's quite strange to get it… I'm still waiting for a procmon to get more details here.
