### ISSUE TITLE
System.ArgumentException: Invalid sample, the metric must NOT be equal zero.

### ISSUE THREAD

**Issue by jwdj** [microsoft/perfview#917]
As requested by Adam Sitnick here is a new perfview issue.
When exporting to Speedscope format the following exception occurs (on an Intel i7 Skylake). It was reproducable (every time) but the application that was profiled is not publicly available so I cannot give you a repro.
The problem is solved (obviously) when SpeedScopeStackSourceWriter.AddEvents just returns instead of throwing the exception. When the duration of the event is 0.0 then it probably is not worth the trouble, so it seems a viable solution to me.

Here is the StackTrace:

System.ArgumentException: Invalid sample, the metric must NOT be equal zero.

Parameter name: closeSample

   at Microsoft.Diagnostics.Tracing.Stacks.Formats.SpeedScopeStackSourceWriter.AddEvents(List`1 profileEvents, Sample openSample, Sample closeSample, Int32 frameId)

   at Microsoft.Diagnostics.Tracing.Stacks.Formats.SpeedScopeStackSourceWriter.GetAggregatedOrderedProfileEvents(IReadOnlyDictionary`2 frameIdToSamples)

   at Microsoft.Diagnostics.Tracing.Stacks.Formats.SpeedScopeStackSourceWriter.Export(StackSource source, TextWriter writer, String name)

   at Microsoft.Diagnostics.Tracing.Stacks.Formats.SpeedScopeStackSourceWriter.WriteStackViewAsJson(StackSource source, String filePath)

   at PerfView.StackWindow.DoSave(Object sender, RoutedEventArgs e)

**Comment by OnurGumus** [comment]
This issue still exists :(
