### ISSUE TITLE
System.NullReferenceException while taking heap snapshot

### ISSUE THREAD

**Issue by jtbm37** [microsoft/perfview#951]
Version: P2.0.42 (64 bit)
Max Dump K objects: 250
Freeze: No
Save ETL: No

Tail of log:
```
1070.1s: Dumped 114,354,847 objects, max_dump_limit 134,217,716 Dumper heap Size 7,384MB
HeapDump Error: System.NullReferenceException: Object reference not set to an instance of an object.
   at System.Collections.Generic.SegmentedList`1.Add(T item)
   at Graphs.Node.WriteCompressedInt(SegmentedMemoryStreamWriter writer, Int32 value)
   at Graphs.Graph.SetNodeTypeAndSize(NodeIndex nodeIndex, NodeTypeIndex typeIndex, Int32 sizeInBytes)
   at Graphs.Graph.SetNode(NodeIndex nodeIndex, NodeTypeIndex typeIndex, Int32 sizeInBytes, GrowableArray`1 children)
   at GCHeapDumper.DumpAllSegments()
   at GCHeapDumper.DumpDotNetHeapDataWorker(ClrHeap heap, ICorDebugProcess& debugProcess, Boolean isDump, Double retryScale)
   at GCHeapDumper.DumpDotNetHeapData(ClrHeap heap, ICorDebugProcess& debugProcess, Boolean isDump)
   at GCHeapDumper.TryGetDotNetDump(Int32 processID)
   at GCHeapDumper.CaptureLiveHeapDump(Int32 processID)
   at GCHeapDumper.DumpLiveHeap(Int32 processID)
   at Program.MainWorker(String[] args)


Completed: Dumping GC Heap to c:\temp\20190613.gcDump   (Elapsed Time: 1071.709 sec)
Error: HeapDump failed with exit code 1
```

**Comment by tiago-soczek** [comment]
Hello, I have the same issue:

```
Started with command line: "E:\Util\PerfView.exe" 
PerfView Version: 2.0.49  BuildDate: Thu, 09 Jan 2020 10:57:19 GMT
PerfView Start Time 2/17/2020 2:05:41 PM
Warning: PdbScope not found at E:\Util\PerfViewExtensions\PdbScope.exe
Disabling the Image Size Menu Item.
Warning: ILSize not found at E:\Util\PerfViewExtensions\ILSize.dll
Disabling the IL Size Menu Item.
Started: View
Completed: View   (Elapsed Time: 0.094 sec)
Started: Dumping GC Heap to E:\Util\X.Server.gcDump
Collecting a GC Heap SnapShot for process 9012
[Taking heap snapshot of process '9012' ID 9012 to X.Server.gcdump.  This can take 10s of seconds to minutes.]
During the dump the process will be frozen.   If the dump is aborted, the process being dumped will need to be killed.
Starting dump at 2/17/2020 2:06:44 PM
Starting Heap dump on Process 9012 running architecture Amd64.
set _NT_SYMBOL_PATH=;SRV*C:\Users\USERx\AppData\Local\Temp\2\SymbolCache*http://msdl.microsoft.com/download/symbols;SRV*C:\Users\USERx\AppData\Local\Temp\2\SymbolCache*https://nuget.smbsrc.net;SRV*C:\Users\USERx\AppData\Local\Temp\2\SymbolCache*http://referencesource.microsoft.com/symbols;SRV*C:\Users\USERx\AppData\Local\Temp\2\SymbolCache*https://dotnet.myget.org/F/dotnet-core/symbols
Exec: "C:\Users\USERx\AppData\Roaming\PerfView\VER.2020-02-17.14.03.49.464\amd64\HeapDump.exe"  /MaxDumpCountK=1000 "9012" "X.Server.gcdump"
Dumping process 9012 with id 9012.
Process Has DotNet: True Has JScript: False Has ClrDll: True HasMrt False HasCoreClr False
*****  Attempting a .NET Heap Dump.
Enumerating over 1 detected runtimes...
/Freeze not present, skipping Debugger attach.
Creating Runtime access object for runtime v4.7.3468.00.
DumpDotNetHeapData: Heap Size 2 MB
Dumping GC heap, This process is a 64 bit process on a 64 bit OS
  0.3s: Starting heap dump 2/17/2020 2:06:48 PM
  0.3s: Size of heap = 53.115 GB
In a 64 bit process.  Increasing the max node count to 134.2 Meg
Implicitly limit the number of nodes to 134.2 Meg to avoid arrays that are too large
Estimated number of objects = 829,927,381
Limiting object count to 134,217,716
DumpDotNetHeapDataWorker: Heap Size of dumper 5,939 MB
A total of 225 segments.
Segment: Start      1e900001000 Length:          fffea08     268.430M LOH:False
.
.
.
.
Segment: Total                  Length:        c5debf568  53,115.352M
  4.0s: Scanning Named GC roots
  4.0s: Scanning UNNAMED GC roots
  6.1s: Scanned 1024 roots.
  6.9s: Scanned 2048 roots.
  7.9s: Scanned 3072 roots.
  8.0s: Scanned 4096 roots.
  8.0s: Scanned 5120 roots.
Scanning UNNAMED GC roots took 5,961.9 msec
  9.9s: Starting GC Graph Traversal.  This can take a while...
Dumping 225 GC segments in the heap in bulk.
[  9.9s: Dumping segment 0 of 225 start: 1e900001000 len: 268.43M]
.
.
.
.
949.3s: Dumped 122,360,279 objects, max_dump_limit 134,217,716 Dumper heap Size 8,181MB
949.4s: Dumped 122,373,836 objects, max_dump_limit 134,217,716 Dumper heap Size 8,184MB
949.5s: Dumped 122,387,415 objects, max_dump_limit 134,217,716 Dumper heap Size 8,187MB
949.6s: Dumped 122,400,912 objects, max_dump_limit 134,217,716 Dumper heap Size 8,183MB
HeapDump Error (-2147467261): System.NullReferenceException: Object reference not set to an instance of an object.
   at System.Collections.Generic.SegmentedList`1.Add(T item)
   at Graphs.Node.WriteCompressedInt(SegmentedMemoryStreamWriter writer, Int32 value)
   at Graphs.Graph.SetNode(NodeIndex nodeIndex, NodeTypeIndex typeIndex, Int32 sizeInBytes, GrowableArray`1 children)
   at GCHeapDumper.DumpAllSegments()
   at GCHeapDumper.DumpDotNetHeapDataWorker(ClrHeap heap, ICorDebugProcess& debugProcess, Boolean isDump, Double retryScale)
   at GCHeapDumper.DumpDotNetHeapData(ClrHeap heap, ICorDebugProcess& debugProcess, Boolean isDump)
   at GCHeapDumper.TryGetDotNetDump(Int32 processID)
   at GCHeapDumper.CaptureLiveHeapDump(Int32 processID)
   at GCHeapDumper.DumpLiveHeap(Int32 processID)
   at Program.MainWorker(String[] args)
```
