### ISSUE TITLE
Thrown exception when saving view to speedscope json

### ISSUE THREAD

**Issue by kzeitz** [microsoft/perfview#956]
Received this when attempting to save to speedscope json format

StackTrace:
System.ArgumentException: Invalid sample, the metric must NOT be equal zero.
Parameter name: closeSample
   at Microsoft.Diagnostics.Tracing.Stacks.Formats.SpeedScopeStackSourceWriter.AddEvents(List`1 profileEvents, Sample openSample, Sample closeSample, Int32 frameId)
   at Microsoft.Diagnostics.Tracing.Stacks.Formats.SpeedScopeStackSourceWriter.GetAggregatedOrderedProfileEvents(IReadOnlyDictionary`2 frameIdToSamples)
   at Microsoft.Diagnostics.Tracing.Stacks.Formats.SpeedScopeStackSourceWriter.Export(StackSource source, TextWriter writer, String name)
   at Microsoft.Diagnostics.Tracing.Stacks.Formats.SpeedScopeStackSourceWriter.WriteStackViewAsJson(StackSource source, String filePath)
   at PerfView.StackWindow.DoSave(Object sender, RoutedEventArgs e)
   at PerfView.StackWindow.DoSaveAs(Object sender, RoutedEventArgs e)
   at System.Windows.Input.CommandBinding.OnExecuted(Object sender, ExecutedRoutedEventArgs e)
   at System.Windows.Input.CommandManager.ExecuteCommandBinding(Object sender, ExecutedRoutedEventArgs e, CommandBinding commandBinding)
   at System.Windows.Input.CommandManager.FindCommandBinding(CommandBindingCollection commandBindings, Object sender, RoutedEventArgs e, ICommand command, Boolean execute)
   at System.Windows.Input.CommandManager.FindCommandBinding(Object sender, RoutedEventArgs e, ICommand command, Boolean execute)
   at System.Windows.Input.CommandManager.OnExecuted(Object sender, ExecutedRoutedEventArgs e)
   at System.Windows.UIElement.OnExecutedThunk(Object sender, ExecutedRoutedEventArgs e)
   at System.Windows.Input.ExecutedRoutedEventArgs.InvokeEventHandler(Delegate genericHandler, Object target)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseEvent(RoutedEventArgs args, Boolean trusted)
   at System.Windows.Input.RoutedCommand.ExecuteImpl(Object parameter, IInputElement target, Boolean userInitiated)
   at System.Windows.Input.RoutedCommand.ExecuteCore(Object parameter, IInputElement target, Boolean userInitiated)
   at MS.Internal.Commands.CommandHelpers.CriticalExecuteCommandSource(ICommandSource commandSource, Boolean userInitiated)
   at System.Windows.Controls.MenuItem.InvokeClickAfterRender(Object arg)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by kzeitz** [comment]
Awesome thanks!
